### ISSUE TITLE
Process termination signal

### ISSUE THREAD

**Issue by richardkazuomiller** [Microsoft/vscode-node-debug#1]
Hi! I just installed Code and first impressions are very good (^_^)

A problem I ran into is that stopping the process with Code uses the `KILL (9)` signal in `terminateProcess.sh` which kills the process immediately. My application listens for `SIGINT`/`SIGTERM` and stops servers and queues gracefully, but `SIGKILL` cannot be listened to so I can't do this when using the debugger. Would it be possible/easy to add an option to define how the process is killed or would it cause issues with the debugger if the process does not immediately die when the stop button is pressed? 

For context, this is my code that handles exiting the process

```
var server = require('../lib/server') // an HTTP server
server.listen(8000)
process.on('SIGINT', function() {
  console.log('Got SIGINT.');
  server.close() //keeps the process alive until all connections are closed
});
```

**Comment by devnieL** [comment]
How did you solve it ?

Thanks

**Comment by richardkazuomiller** [comment]
I didn't really, but it's not a big deal. I just don't use vscode to test this part of my application.

**Comment by offero** [comment]
I am dealing with the same issue now.

**Comment by jpenna** [comment]
Any update on this?

**Comment by ipengyo** [comment]
Hello, I also encountered the same problem

**Comment by vit100** [comment]
I have to use taskkill /im node.exe /F in windows.
Bad thing it kills all node processes, so if you have couple servers working and debugging only one, this will kill all of them. -((

**Comment by royalrover** [comment]
yes，i encounter the same problem

**Comment by weinand** [comment]
I'd like to address this issue in the following way:
- we introduce a new "softKill" option to the DAP's "disconnect" request (and a corresponding capability)
- if a debug adapter supports "softKill", VS Code's red terminate button will first send a "softKill" disconnect to the DA, which results in a `SIGINT` signal sent to the debuggee.
- If the debuggee has no `SIGINT` handler, the debuggee will terminate and end the debug session. This is almost identical to the current behaviour.
- if the debuggee has a `SIGINT` handler but doesn't terminate properly, the debug session will continue. Pressing the red terminate button again will send a "disconnect" request without the "softKill" option. This will kill the debuggee forcefully (like the current behaviour).

@roblourens @isidorn what do you think?

**Comment by roblourens** [comment]
Sounds good to me!

**Comment by weinand** [comment]
After some discussion and source code analysis with @isidorn, w've decided to use an approach that does not interfere with the semantics of the existing 'disconnect' request.

- we introduce a new `terminate` request and a corresponding capability `supportsTerminateRequest` to the DAP. This request is used to give the debuggee a chance to shutdown itself in a graceful way.
- if a debug adapter supports "terminate", VS Code's red terminate button will first send a "terminate" request to the DA (which some DAs might implement by sending a `SIGINT` signal to the debuggee). VS Code remembers in its debug session state that a "terminate" request has been issued.
- If the debuggee has no `SIGINT` handler, the debuggee will terminate and end the debug session. This is almost identical to the current behaviour.
- if the debuggee has a `SIGINT` handler but doesn't terminate properly, the debug session will continue. Pressing the red terminate button again will send a "disconnect" request. This will kill the debuggee forcefully (like the current behaviour).

@isidorn I've added a terminate to VA Code's DAP.

**Comment by maximedupre** [comment]
I'm a bit confused. Is it possible to use the "terminate" option with the native vsc node debugger, with the latest version (`v1.25.1`)? If so, what attribute do I need to add in my launch config? Thank you for this very helpful feature!

**Comment by isidorn** [comment]
@maximedupre this is currently only available in vscode insiders.
It will be avilable in the next stable relase in about 10 days.

**Comment by weinand** [comment]
@maximedupre and you don't have to change anything on your side.
