### ISSUE TITLE
[Windows 10] Stack traces come out without a "source"

### ISSUE THREAD

**Issue by RaniSharim** [Microsoft/vscode-node-debug#100]
This eventually causes a weird behavior when hitting breakpoints in vscode as described in https://github.com/Microsoft/vscode/issues/10610

If someone can tell me how to debug the vscode-node-debug extension itself I can try to investigate further.

Otherwise, there is a repo where you can reproduce the problem here:
 https://github.com/RaniSharim/testproject.git
the file is routes/officemanagement.js, just try to hit a breakpoint on the single function that exists there.

**Comment by weinand** [comment]
Should be fixed by now.
