### ISSUE TITLE
Downloaded sourcemap cache invalidation

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-node-debug#102]
node-debug has some code that writes downloaded sourcemaps to a file, by a hash of the path, and reads them from there later if they are available. I copied that code and later realized that nothing in my code is clearing these out if the sourcemap has changed, and I think the same is true in node-debug. Or am I missing something? This is probably not a problem for Node cases like in vscode where the url is pointing to some bucket for production sourcemaps that don't change.

It is a problem for Chrome where urls are used most of the time for development, so I might have to disable it for Node, or include a hash of the file contents.

**Comment by roblourens** [comment]
For future reference, pretty sure this is relevant to Microsoft/vscode-chrome-debug#247

**Comment by orehmane** [comment]
Has this feature been released or no? It seems like the last activity was a little under a year ago.

**Comment by weinand** [comment]
no intentions to fix this for legacy node-debug.
