### ISSUE TITLE
Wrong value show for `this` on hover in es6 arrow syntax

### ISSUE THREAD

**Issue by ventsislav-georgiev** [Microsoft/vscode-node-debug#103]
The **ES6** `arrow syntax` preserves `this` to be the parent scope. However, in VSCode node debugging the on hover provider shows the `bind`-ed value of `this`, which is really confusing while debugging.

![image](https://cloud.githubusercontent.com/assets/5616486/19479439/69c70a20-954f-11e6-9df3-351e68782a54.png)
> Note: that evaluation or `console.log` in the debug console shows the correct value of `this`.

**VSCode version:**
1.6.1

**Node Debug version:**
1.6.10

**Code to reproduce**
```js
(function() { 
	console.log(`parentScope: ${this.fake}`);

	(() => { 
		console.log(`childScope: ${this.fake}`);
		debugger;
	}).call({ innerFake: "innerFakeValue" }); 

}).call({ fake: "fakeValue" });
```

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#13967

**Comment by weinand** [comment]
This is a problem of the debugger UI.
