### ISSUE TITLE
Object previews can be very large

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#107]
It's limited by number of props, but prints the full value, so maybe the per-property length should be limited? Would also address #106.

![image](https://cloud.githubusercontent.com/assets/323878/19583052/4c868d14-96ee-11e6-9d49-ae0c5b5a07bf.png)

**Comment by roblourens** [comment]
Chrome DevTools truncates large string props in the middle, and does not recurse to show previews of object/array props. I like doing that though.

**Comment by weinand** [comment]
Another bug related to https://github.com/Microsoft/vscode/issues/14305
