### ISSUE TITLE
Unable to debug Webpack bundled code

### ISSUE THREAD

**Issue by ligaz** [microsoft/vscode-node-debug#109]
It looks there is no way to debug code that is generated from Webpack due to the way Webpack generate source maps (using `webpack://` protocol). Do you plan to support it?

**Comment by TimBo93** [comment]
for me webpack works without any issues...

**Comment by ligaz** [comment]
@TimBo93 Can you please share your Webpack configuration and `launch.json` file? Thanks.

**Comment by TimBo93** [comment]
Maybe this can help you ..
[https://github.com/TimBo93/MinimalTsAngularSPA](url)

**Comment by ligaz** [comment]
It looks like you are using Webpack Dev Server and not having any backend code. 

The issue I'm observing is that I'm unable to debug my Express application that is bundled with Webpack.

**Comment by TimBo93** [comment]
sorry if if missunderstood you.

my index.html includes (only for development) from several sources. For example SignalR is will be loaded from the asp.net Server, while die bundle.js is loaded from webpack-dev-server.
```
<script src="Scripts/jquery.signalR-2.2.1.js"></script>
<script src="signalr/hubs"></script>
<script src="http://localhost:8080/bundle.js"></script>

```

Of course i can debug the files generated by webpack in this scenario only.

**Comment by ligaz** [comment]
It looks like there is a way to make this work using `devtoolModuleFilenameTemplate` configuration for Webpack's output. More info [here](http://stackoverflow.com/questions/36470946/debug-webpack-bundled-node-ts-with-visual-studio-code).
