### ISSUE TITLE
Slow & unresponsive debugging

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-node-debug#116]
it seems the [vscode/6244](/Microsoft/vscode/issues/6244) is back. All symptoms are the same. Debugging became extremely unresponsive and slow. Data gets lost: sometimes I get <...>, sometimes something like <... because Node.js is unresponsive>. Both via debug panel or via hovering over code.
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-12/2016-12-14_07-33-43.gif)
In this clip I hover over ``render(what...`` and the cursor dissapears - it is a recording glitch. the cursor was the whole time over the ``what``.

**Comment by Spown** [comment]
sometimes I get this in console after trying to evaluate ``timeout after 10000 ms``

**Comment by weinand** [comment]
This slowness is a problem of the (obsolete) v8 debugging protocol. 
Please use the `node2` debugger. See https://code.visualstudio.com/docs/editor/node-debugging#_experimental-nodejs-debugger-node2
