### ISSUE TITLE
Breakpoints not working correctly with browserified/babelified code

### ISSUE THREAD

**Issue by riverar** [microsoft/vscode-node-debug#119]
I'm still hunting down source map bugs but wanted to get this test case out there.

Steps:
- Clone https://github.com/riverar/vscode-testcase01
- `npm install`, this will compile `{workspaceRoot}/src/app.js` to `{workspaceRoot}/app.js` with a source map containing relative source paths (i.e. app.js)
- Set a breakpoint on the first line in the source app.js (i.e. `console.log('hello')`)
- Start debugging with Launch Program configuration (you may need to adjust launch ports)
- Note breakpoint is never hit

Ok, you're probably thinking -- we're missing the `src/` path in the source map, so that's not a surprising result, given the scriptRegExp the debugger builds up. Let's turn on absolute paths, should work great then.

Steps:
- `npm run build-absolute`, this will replace app.js with a copy containing a source map w/ absolute source paths
- Restart debug session per above steps
- Note breakpoint still isn't hitting 😡 

Is there a scenario where source map debugging actually works (in the launch configuration)?

My next case will involve fiddling with local/remote root overrides in the attach configuration. Stay tuned.

**Comment by roblourens** [comment]
In the first case, I see the sourcemap with these contents:

```
'{"version":3,"sources":["../node_modules/browser-pack/_prelude.js","app.js"],"names":[],"mappings":"AAAA;;;ACAA,QAAQ,GAAR,CAAY,OAAZ;AACA,QAAQ,GAAR,CAAY,OAAZ","file":"generated.js","sourceRoot":""}'
```

That's not correct because it needs to point to the app.js in the src folder.

In the second case, I end up with the same thing. Not sure what's wrong.

**Comment by riverar** [comment]
@roblourens Oh, I submitted a change to frida-compile to support that `-a` and it hasn't been pushed to npm yet. 😆 

I checked in the absolute app.js for the meantime. Instructions updated above.

**Comment by riverar** [comment]
Obligatory system information
```
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:49:23.350Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
Windows 10 1607 14986.1001
```

**Comment by riverar** [comment]
I just realized that absolute js will need some obvious tweaking to match a path on your system.

**Comment by roblourens** [comment]
Can you also try that case with `"type": "node2"` instead of node?

**Comment by riverar** [comment]
`frida-compile` was pushed to npm, so you get the -a now, if you want to try that second scenario w/o having to tweak the absolute path manually. (Just run `npm install frida-compile` and `npm run build-absolute`.)

I can confirm debugger `node2` works, but doesn't help me as I'm attaching to a process that hosts the V8 debugger. Upgrading to CDP is in the cards but we're not there yet.

Looks like a scriptRegExp breakpoint request is made containing an absolute path in all scenarios, which doesn't seem correct.

**Comment by jasonwilliams** [comment]
Is it related to this? https://github.com/ChromeDevTools/devtools-protocol/issues/103#issuecomment-421183542
