### ISSUE TITLE
How to simply debug a file

### ISSUE THREAD

**Issue by pannous** [Microsoft/vscode-node-debug#122]
Is it possible to simply debug a JavaScript file without creating a project and project configuration etc. ?

**Comment by weinand** [comment]
@pannous what exactly do you mean by project and project configuration?

**Comment by pannous** [comment]
I think launch.conf is the file that needs to be created in order to debug a JavaScript file?

**Comment by pannous** [comment]
By now this issue is probably a feature request, unless I overlooked something.

**Comment by weinand** [comment]
In the January release we'll add a feature that eliminates the need for a launch.json for simple cases. Debug extension will have to opt-in, so initially it is only supported by the node and PowerShell debuggers.

**Comment by pannous** [comment]
perfect, thanks!!

**Comment by weinand** [comment]
this is the corresponding feature: https://github.com/Microsoft/vscode/issues/285
