### ISSUE TITLE
Add log message when 'protocol' is inferred

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#126]
In the debug console, "Debugging with the legacy protocol because Node v5.1.0 was detected"

**Comment by roblourens** [comment]
Since startSessionCommand probably can't write to the debug console, there could be a hidden prop on the launch config that it sets, telling the debug adapter whether 'protocol' was inferred and how.

**Comment by weinand** [comment]
@roblourens I've added a VS Code feature request: https://github.com/Microsoft/vscode/issues/20113

**Comment by weinand** [comment]
@roblourens I will add this messages to better understand what we need to do here...

**Comment by weinand** [comment]
Added some information messages to the protocol guessing code and pass them through the launch config as an `--information` attribute which node-debug sends to the debug console.
Will covert as soon as Microsoft/vscode#20113 has been implemented.
