### ISSUE TITLE
"Open loaded scripts" doesn't show eval scripts

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#134]
- Debug node app with eval('debugger')
- When the debugger stops in in the eval script named VM#, invoke Open Loaded Scripts
- There is no script with the name of the eval script

**Comment by weinand** [comment]
@roblourens I'm treating now eval scripts (i.e. scripts without a name), as regular internal modules. So their path has the form "<node_internal>/VMnnn" (where 'nnn' is the script's ID). The "Open loaded scripts" command now shows them like this:

![2017-04-18_16-39-50](https://cloud.githubusercontent.com/assets/1898161/25140671/6cd16854-2461-11e7-8969-9433a810f7a9.png)

You might want to change this for the 'inspector' protocol too.

**Comment by roblourens** [comment]
Should they be marked as 'node_internals', which I think implies that it's owned by node? These will often be user scripts.

**Comment by weinand** [comment]
Today 'node_internals' is used to indicate that the JavaScript runtime does not provide an (absolute) file system location for a script. The unnamed scripts from evals match that definition but I agree that 'node_internals' is not the best name for conveying that semantics. 

Do you think it is worthwhile to:
- fix the 'node_internals' prefix to better convey the semantics,
- add another prefix,
- keep the 'node_internals' prefix and include the "VMnnn" scripts under it.

As a pragmatic, I'm fine with the third option.

**Comment by roblourens** [comment]
I think the 'VM' is sort of already a prefix, and I'll probably leave the inspector adapter alone, but I think it's not a big deal either way, and node-debug can stick with the third option.

**Comment by roblourens** [comment]
Although, if a script is evaled with a `sourceURL` to give it a non-absolute-path name, then it ends up with `<node_internals>` too anyway, since I can't tell the difference. https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Debug_eval_sources
