### ISSUE TITLE
After unchecking `All Exceptions` during debug session, it still breaks on caught exceptions

### ISSUE THREAD

**Issue by sbj42** [Microsoft/vscode-node-debug#135]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Home

#### Description
The `All Exceptions` breakpoint checkbox causes the debugger to break on caught exceptions.  However during a debug session, once it is checked, unchecking it seems to have no effect.  The debugger will still break at the next caught exception.

#### Complete example
I've put a complete demonstration of the problem at [this github repo](https://github.com/sbj42/vscode-ts-debug2), steps to reproduce are in the README there.

#### Steps to reproduce
1. Using the `test.ts` file below, start a debug session with `All Exceptions` checked.
2. It will break correctly at the "oops1" throw.
3. Now uncheck `All Exceptions` and continue.
4. It breaks at the "oops2" throw, even though that exception is caught.

`test.ts`:
```ts
try {
    throw new Error('oops1');
} catch (e) {
    // do nothing
}

try {
    throw new Error('oops2');
} catch (e) {
    // do nothing
}

throw new Error('oops3');
```

**Comment by weinand** [comment]
@sbj42 what version of node are you using?

I cannot reproduce the problem with VS Code  1.11.1 and node 7.4.0

**Comment by roblourens** [comment]
I have seen this while debugging the extensionHost, btw. Not a normal node app. cc @chrmarti

**Comment by sbj42** [comment]
`node -v` says 6.7.0, and the debug console said:
~~~
Debugging with legacy protocol because Node v6.7.0 was detected.
~~~
VSCode "About" dialog says 1.11.2, and Node 6.5.0.
Tried it again to make sure, still reproduces:

![vscode-node-debug-135](https://cloud.githubusercontent.com/assets/99791/25027170/bbb895c4-2078-11e7-92c6-581ab8c5f730.gif)

**Comment by sbj42** [comment]
@weinand Is that information sufficient?

**Comment by weinand** [comment]
@sbj42 yes, I could reproduce after I'd noticed in the screencast that "Uncaught Exceptions" needs to be checked too. In your original description you said "start a debug session with All Exceptions checked." which I'd interpreted as "start a debug session with **only** All Exceptions checked."

The bug will be fixed in tomorrows Insiders.
