### ISSUE TITLE
Translation for "Node" too literal in German

### ISSUE THREAD

**Issue by fttr** [Microsoft/vscode-node-debug#138]
Should be "Node" instead of "Knoten" for the following keys:

- protocol.switch.inspector.version
- protocol.switch.legacy.version

File: 
vscode-node-debug/i18n/deu/out/node/extension.i18n.json

**Comment by marvinhagemeister** [comment]
Can confirm, we germans often leave technical terms as is.

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/24416
