### ISSUE TITLE
Debugging not working after 1.11.2 update?

### ISSUE THREAD

**Issue by indigox4** [Microsoft/vscode-node-debug#141]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|;

---
Node version 6.2 
Express version 4.10.2
Sockets.io version 1.4.6

Steps to Reproduce:

1. Clone https://github.com/indigox4/TicTacToe
2. Open visual studio code. 
3. Set breakpoint in index.js around line 244
4. Press F5 to start debugging
5. Open chrome, point it to localhost:3000
6. Try to login with any name and password.

Note that the vsc debugger breaks, but debugging does not seem to work. No line is highlighted, nor can I step into or over any lines in the text editor, or inspect the value of any variables.

In the call stack view I see:
No call stack available (backtrace; internal error; illegal access)

I think this started happening with the 1.11.2 update.

**Comment by neenhouse** [comment]
@indigox4 - Having same issue in 1.14.2 + node 6.8.1/6.11.0

**Comment by weinand** [comment]
@indigox4 @neenhouse I cannot reproduce your problem in VS Code 1.14.2 and node 6.2/6.8.1/6.11 on WIndows 10.

![2017-08-08_15-24-41](https://user-images.githubusercontent.com/1898161/29073987-033e9afc-7c4e-11e7-824b-69abb239a406.gif)

**Comment by indigox4** [comment]
@weinand Updating node to 6.10.2 seemed to fix the issue for me.  Thanks for investigating.
