### ISSUE TITLE
Launch style debugging with nodemon + restart is flaky / not working

### ISSUE THREAD

**Issue by stepro** [microsoft/vscode-node-debug#143]
Please see branch "local" of this repo: https://github.com/stepro/my-express-app

After cloning, open in VS Code and hit F5. This uses a launch-style request to debug via "npm run debug", which launches nodemon. If you change app.js during debugging, nodemon restarts the process. On Mac, VS Code is sometimes successful in restarting the debugger and attaching to the new process, however it often ends up with the whole process tree dying and it's unable to attach to the socket. On Windows, it never works.

**Comment by stepro** [comment]
I've since updated the repo to avoid the problem. To see the broken state, check out commit 98399b1.

**Comment by weinand** [comment]
I've been on vacation. Will look into this any day now...

**Comment by stepro** [comment]
I've been iterating a bunch on the repo I provided. Here's the latest repo information. On a Windows machine, clone https://github.com/stepro/my-express-app. Git checkout the docker-compose branch. Open the latest version of VS Code and launch the debugger using the "Node.js launch (docker-compose)" launch settings. At least for me, without fail, this starts the process but fails to attach.

The reason for this is due to an intermediate state for the Node debugging port exposed on the host. With Docker for Windows, when a container starts up with a host port mapping, Docker for Windows starts listening on that port immediately whether the container is actually listening on it or not. In this state, clients can connect to the TCP port, but the server-side immediately closes the connection.

VS Code does not recognize this intermediate state for ports and thinks that the debuggee terminated. I worked around the problem by forcing VS Code to wait to try and connect to the port until the launched Node.js process outputs "Debugger listening on ". This worked, but is kind of hacky. It's probably better if VS Code is able to treat a successful TCP connect followed by an immediate terminate as equivalent to the port being unavailable, and keep retrying until it is actually successful.

**Comment by stepro** [comment]
I actually just verified that the same issue with Docker exists on Mac. Here's a simple repo.

Run `docker run -p 3000:3000 -d alpine sleep 100000`. This starts up a container with a process that clearly doesn't listen on any particular port, but a container port is mapped to host port 3000. Once this container is up and running, run `curl localhost:3000 -v`. You'll see output like:

```
* Rebuilt URL to: localhost:3000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.51.0
> Accept: */*
> 
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

The server (the Docker daemon) simply closes the connection.

**Comment by joshua-fogg** [comment]
bump

**Comment by weinand** [comment]
Have you tried the „restart“ option?

**Comment by connor4312** [comment]
We now have a [new debugger](https://github.com/microsoft/vscode-js-debug/) that can handle nodemon in a more resilient way. Please open an issue on that repo if you still run into problems.
