### ISSUE TITLE
Support for multi level of source maps.

### ISSUE THREAD

**Issue by niba** [Microsoft/vscode-node-debug#145]
In my project, I compile my code twice using Typescript and then Babel so the flow is [TypescriptFiles -> TypescriptOutput -> BabelOutput]. Each output has different directory so the Typescript writes to `out-typescript` directory and Babel to `out`. Typescript and Babel produce sourcemaps. I'm having a problem with setting breakpoints. The debugger loads all of the source maps from both directories but doesn't map breakpoints more than once. I mean when I put a breakpoint on example.ts file, the debugger will set the breakpoint on the example.js generated by typescript but it won't repeat that operation for the output file generated by babel.  
Of course, I'm running code produced by Babel and right now I can only debug by setting breakpoints on Typescript output files.
Is it possible to configure it somehow and map breakpoints through two files?

**Comment by roblourens** [comment]
I recommend setting up your build to produce a single sourcemap that maps end to end. This is possible depending on the tools you're using. I recommend using a task runner or bundler like gulp or webpack.
