### ISSUE TITLE
Full path in debug callstack

### ISSUE THREAD

**Issue by ubershmekel** [Microsoft/vscode-node-debug#146]
I have an app with `index.js` that's calling my library that has an entry point of `index.js` which relies on `node_modules/express/lib/router/index.js` so my stack trace is entirely `index.js` with no way of telling which part of it is actually in my code.

Is there a way to give a user-configurable option or perhaps expand the path when there's room for it?

![index.js](http://i.imgur.com/v0lJZb7.png)

Related to:
* https://github.com/Microsoft/vscode-node-debug/commit/c4a38ad0c70dccbb3b35c0ab5cd44891541dc300
* https://github.com/Microsoft/vscode/issues/18447

**Comment by weinand** [comment]
You can hover over the name to see the full path of the name.

**Comment by weinand** [comment]
I'm move this request over to VS Code because this is a general debug UI issue and not node-debug specific.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#30686
