### ISSUE TITLE
Launch debugger via docker/docker-compose doesn't work with PID retrieval/kill

### ISSUE THREAD

**Issue by stepro** [microsoft/vscode-node-debug#149]
Currently the Node debugger will ask the debuggee for its PID, and then if you click to stop debugging, it will kill the process with that PID. This is inherently problematic when the controlling process isn't node itself but something else that ultimately spawns node on what is in effect a different machine. In the case of a Docker container, it's extremely problematic if the node process ends up being PID 1 (a common best practice for containers due to signaling requirements) and VS Code attempts to kill PID 1. This does in fact "work" on a Mac but puts the whole system into an unstable state.

I'm not sure what to do about this other than perhaps checking information about the PID to be killed to make sure it's actually a node process. If not, perhaps it would be best to fall back to using the PID of the originally launched process, in this case a docker or docker-compose process? As it stands, stopping debugging doesn't actually stop the process.

**Comment by weinand** [comment]
With the advent of the "Remote - Containers" extension this is no longer a problem.
