### ISSUE TITLE
Localization for menu items seem not working properly

### ISSUE THREAD

**Issue by leftstick** [Microsoft/vscode-node-debug#151]
When i changed my `locale.json` into Chinese mode `"locale":"zh-CN"`, i found menu item `extension.node-debug.toggleSkippingFile` displayed in english, even the rest items are changed.

The translation [chs-package.i18n.json](https://github.com/Microsoft/vscode-node-debug/blob/master/i18n/chs/package.i18n.json) seems not working?

![screen shot 2017-06-27 at 4 01 55 pm](https://user-images.githubusercontent.com/1059956/27577283-a96bdc90-5b52-11e7-8074-c6244010edb6.png)

OS: macOS Sierra 10.12.1
vscode: 1.13.1

**Comment by weinand** [comment]
"Toggle Skipping This File" is node-debug2.
node-debug uses the correct "Toggle Skipping this File" (and has translation).

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug2#124
