### ISSUE TITLE
Support hex value display in debugger

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode-node-debug#155]
I'm looking for the ability to display values in hexadecimal while debugging a Node.js app.   According to comments in Microsoft/vscode#28025 this capability needs to come from the debugger extension.

**Comment by fordp2002** [comment]
I like this when debugging Python, C and C++. I suspect it should be done centrally in VS Code as adding it to every debugger is a dumb way to do it!

**Comment by weinand** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding
