### ISSUE TITLE
Node process is not killed while using wsl

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-node-debug#163]
Hello,
I am using the following configuration to run debug using node installed on wsl
"type": "node",
"request": "launch",
"name": "Node server.js",
"useWSL": true,
"program": "${workspaceRoot}/server.js",
"protocol": "inspector"
Which works fine.
However even after i stop the debugger the node process in the task manager is still alive.

**Comment by weinand** [comment]
the "useWSL" attribute is deprecated because VS Code now has the "Remote - WSL" extension.
