### ISSUE TITLE
Be able to use --inspect without --inspect-brk

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode-node-debug#166]
Due to the issue present in:

https://github.com/Microsoft/vscode-node-debug/issues/165

How easy would it be to have a fallback that allows me to just force --inspect and disable --inspect-brk?

**Comment by roblourens** [comment]
You could start it yourself with `--inspect` and use an 'attach' config. Or, you could set `"runtimeArgs": ["--inspect=1234"]` and `"port": 1234`. If you set `port`, the adapter won't add the `--inspect-brk` flag.

**Comment by jpike88** [comment]
This attach config... not sure what you mean?

**Comment by jpike88** [comment]
Ignore that I figured it out, thanks

**Comment by jpike88** [comment]
@roblourens turns out the issue isn't resolved... I need a way to delay the attaching of the debugger as it's interfering with ES6 module initialisation.. thanks anyway
