### ISSUE TITLE
Cannot debug mjs modules

### ISSUE THREAD

**Issue by ThePlenkov** [Microsoft/vscode-node-debug#167]
Hi,

I hope I chose the correct place to create the issue.

I'm trying to debug mjs node file but the breakpoints are just ignored.

Please see attached gif file.
![2017-12-09_10-04-31](https://user-images.githubusercontent.com/6381507/33794258-850f6f4a-dcc8-11e7-91a9-56a77046060b.gif)

This is my configuration:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Test JSDOM",
            "program": "${workspaceFolder}/jsdom.mjs",
            "runtimeArgs": [
                "--experimental-modules"
            ]
        }
    ]
}
```

Do I do something wrongly or it's just not supported yet?

Thank you!

**Comment by ThePlenkov** [comment]
What is interesting. If to put breakpoint into the classic JS module it stops there. And then you can go back.

But in this case you have a different file:
![image](https://user-images.githubusercontent.com/6381507/33795308-473a476e-dcdf-11e7-8855-0b8f11396f25.png)

In this file you can already set breakpoints.

**Comment by roblourens** [comment]
There are two issues with this:

- Node won't pause on start, when using the `--experimental-modules` flag: https://github.com/nodejs/node/issues/17340
- They return module paths in a different format with that flag, which isn't handled properly: https://github.com/Microsoft/vscode-node-debug2/issues/157

**Comment by ThePlenkov** [comment]
@roblourens  the problem is that VS Code debugger even doesn't 
stop on debugger statement, not only on start.

The workaround now is like this: 
I run from terminal
node --inspect --experimental-modules jsdom.mjs

It automatically starts chrome dev tools with my mjs module. (NIM extesnsion do the magic) So finally I develop in VS Code  and debug in Chrome. 

I find a very valuable feature opportunity to debug mjs directly from VS Code.

**Comment by roblourens** [comment]
> @roblourens the problem is that VS Code debugger even doesn't
stop on debugger statement, not only on start.

That's because we start Node in a paused state, then attach. Right now it will skip right over the debugger statement before we are able to attach.

Debugging in Chrome devtools should give a similar experience except for https://github.com/Microsoft/vscode-node-debug2/issues/157.

I will move this bug to the right repo and keep it open to track the upstream issue in Node.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-node-debug2#158

**Comment by ericblade** [comment]
Worth noting that the "runtimeArgs" parameter is not documented at the obvious point in the documentation, https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes

I ended up having to find this bug report to figure out that that parameter exists. I'll see if i can figure out where to properly report that, or fix it if the docs are publicly editable.

**Comment by roblourens** [comment]
That section doesn't list all attributes for Node debugging, just a few that are common among different debug adapters. There's a more exhaustive list of Node-specific launch config attributes here https://code.visualstudio.com/docs/nodejs/nodejs-debugging

**Comment by ericblade** [comment]
Seems that it might be good to have a list of all of the launch.json attributes in a place marked "launch.json attributes" ;-)
