### ISSUE TITLE
Node Debug & Node Debug 2 unexpected activate when I press F5 in a non-node project

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-node-debug#170]
Currently if you open a Dart project and press F5 with no launch json, you see this:

![Unwanted node debugger](https://user-images.githubusercontent.com/1078012/35923250-8ff2bc18-0c17-11e8-973a-34998b25cf88.png)

We're trying to simplify the first debug experience for Dart & Flutter and having nodejs appear here is somewhat confusing. It seems that the extension only activates when you hit F5. My guess is this happens because of this in `package.json`:

```js
"activationEvents": [
     "onDebugInitialConfigurations",
```

This seems somewhat eager and makes a worse user experience for other extensions. Is there a way this could be prevented?

I've also raised https://github.com/Microsoft/vscode/issues/43101 about being able to affect what's displayed here (because we're also trying to avoid Dart/Flutter showing up in the opposite project types) so I don't know if that could also help here (eg. the node debugger would be able to stop itself from appearing in projects that are unrelated).

**Comment by DanTup** [comment]
I believe this was because we didn't have `languages` defined against the debugger in `package.json` so Code was showing them all. After adding the language, it only shows ours.

**Comment by DanTup** [comment]
I actually think there's still something unexpected here.

If I open a Dart project but *do not* have a Dart file open, and then hit F5, I get a choice between Node and Dart debuggers. As far as I can see, there is no reason for the Node debugger to be appearing -my project is not Node/JavaScript.

If the node extension did not activate, then this would remove the step of selecting a debugger which would be a better user experience (it's confusing to users to see an option that won't work for their project).

**Comment by weinand** [comment]
This is the expected behaviour: If a user has no launch.json and VS Code needs to create one, we show all contributed debuggers in the QuickPick.

**Comment by DanTup** [comment]
@weinand Understood; though I think the user experience would be improved if Node didn't show up unless there were some js files in the project or something.
