### ISSUE TITLE
Terminate DA when running without debugging from terminals

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug#172]
When running a program "without debugging" (Control + F5), the DA has no good way to get hold of the process ID of the program (and it will not be able to terminate the program when the red terminate button is pressed).

Consequently we should not keep up a debug session that serves no purpose.

I suggest that a DA sends a "terminate" event in this case (which makes VS Code stop the session silently). 

/cc @roblourens @isidorn

**Comment by isidorn** [comment]
That was fast, 3 minutes from issue to commit

**Comment by weinand** [comment]
actually, I found that slow for a one-liner... ;-)
