### ISSUE TITLE
Multi-root workspace have no way of mentioning project specific files in launch.json

### ISSUE THREAD

**Issue by bhagatparwinder** [Microsoft/vscode-node-debug#173]
**Inroduction**
I and many other developers use dotenv in their node projects to specify configs, endpoints or variables. Here is the repo for dotenv https://github.com/motdotla/dotenv

dotenv is a file at the root of the project (.env) and variables are stored in it as

```
DB_HOST=localhost
DB_USER=root
DB_PASS=s1mpl3
```
Then I can access these variables in my project using `process.env`

**What works**
I have a project called example-project. I open it in VSCode. This project has a .env at root. I created a launch.json for this project. It looks like:

```
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceFolder}/app.ts",
    "outFiles": [
        "${workspaceFolder}/*.js"
    ]
}
```

I go to debug and hit play. It work!

**What does not work**
I open the parent folder of example-project. The parent folder is `parent-folder`. 

This folder has 20 projects. example-project-1, example-project-2 and so on.

This is a multi-root workspace now. When I create a launch.json now, the .vscode folder is created in the `parent-folder`.

Now when I hit play in debug mode I get errors! Here's my `launch.json`

```
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceFolder}/example-project/app.ts",
    "outFiles": [
        "${workspaceFolder}/example-project/*.js"
    ]
}
```

The error I'm getting is

```
Error: ENOENT: no such file or directory, open '.env'
```

And my logic is that the process is trying to find the .env file in `parent-folder` (which does not exist) and not `example-project` (which does exist)

I know this is a long description for the issue but I'm hoping this will help resolve it. Long story short, launch.json in multi-root workspace should honor project paths instead of multi-root path.

**Comment by weinand** [comment]
BTW, VS Code directly supports .env files. Please see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_load-environment-variables-from-external-file-node

**Comment by bhagatparwinder** [comment]
@weinand Thanks for the input. You are correct that I opened the parent folder. I had about ten projects in the workspace, and as projects increased, it became easier to open the parent folder than manually adding them one by one to the workspace file or using "Add Folder to Workspace."

Please allow me till Monday to respond if it fixes the issue or not (once I'm back in the office).

P.S. The support for .env file is amazing. I was not aware of that. Thanks for doing an amazing job 👏🏼 with VS Code!
