### ISSUE TITLE
Debug restart, breakpoint will automatically jump to unknown line

### ISSUE THREAD

**Issue by snoopy83101** [Microsoft/vscode-node-debug#176]
VSCode Version:1.21.1
OS Version:
Steps to Reproduce:

require('babel-register');
require('./server/index.js')

The breakpoint was originally on a line
When debug starts,and refresh the browser, breakpoint  jump to other lines

I must first cancel them and reset them

![image](https://user-images.githubusercontent.com/24613784/38123340-2851d184-340d-11e8-89da-a96e11492bdb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by snoopy83101** [comment]
![image](https://user-images.githubusercontent.com/24613784/38123502-f0f63f12-340d-11e8-8200-fef781275bf6.png)

**Comment by snoopy83101** [comment]
i use vscode insiders now
set 2 breakpoints  in line 212 and 242
and F5
![image](https://user-images.githubusercontent.com/24613784/38124809-4810280e-3417-11e8-89c2-2221ed6a4d38.png)
and Refresh the browser

![image](https://user-images.githubusercontent.com/24613784/38124825-72b6e9d0-3417-11e8-8d8d-d98de0f89a41.png)

see? like this.  
There is no law at all and the breakpoints will jump at random.

**Comment by roblourens** [comment]
Then it is probably this other issue with async/await and babel: https://github.com/Microsoft/vscode/issues/45345
