### ISSUE TITLE
Local root property in nested config file

### ISSUE THREAD

**Issue by radu-matei** [Microsoft/vscode-node-debug#178]
I work on an extension where as part of the config file I pass the actual NodeJS configuration for remote debugging - something along these lines:

```json
        {
            "type": "draft",
            "request": "launch",
            "name": "draft",
            "original-debug": {
                "type": "node",
                "request": "attach",
                "name": "Attach to remote",
                "address": "localhost",
                "port": 9229,
                "localRoot": "${workspaceFolder}",
                "remoteRoot": "/usr/src/app/"
            }
        }
```

The problem is that the value of `localRoot`, `${workspaceFolder}` doesn't seem to get interpreted correctly (my assumption is because it's in a nested object in the config file) - the result is that the breakpoints are not bound.

If I put the absolute path of the directory manually in the file or if I pass the root directory from the extension code (`vscode.workspace.rootPath`) everything works correctly.

Any ideas how I could solve / bypass this issue?

**Comment by weinand** [comment]
I do not really understand the value of nested launch configurations but two important facts to remember:
- variable substitution is generically handled by VS Code independent from a specific debugger. So filing this issue for node-debug doesn't make sense.
- variables are substituted on every level.
