### ISSUE TITLE
Debugging meteor with sourcemaps: package-name with colons crash discovery

### ISSUE THREAD

**Issue by mrsimpson** [Microsoft/vscode-node-debug#179]
## Intention

I'm trying desperately to do server-side-debugging of our application with VSCode. However, breakpoints are never activated (grey circle). 

## Configuration

The launch-config contains some partially commented trial-and-error 

```
{
	"name": "Attach",
	"type": "node",
	"request": "attach",
	"port": 9229,
	"address": "localhost",
	"restart": false,
	"sourceMaps": true,
	// "outFiles": [
	// 			// "${workspaceFolder}.meteor/local/build/programs/server/*.js",
	// 			"${workspaceFolder}.meteor/local/build/programs/server/packages/*.js",
	// 			],
	"localRoot": "${workspaceFolder}",
	"remoteRoot": null,
	"cwd": "${workspaceFolder}",
	"trace": "sm"
 }
```

Our project which I want to debug: https://github.com/assistify/Rocket.Chat
Sample breakpoint in any server-side code, [e. g.](https://github.com/assistify/Rocket.Chat/blob/develop/packages/assistify-ai/server/lib/SmartiAdapter.js#L36)

## Guessing

I have got an idea which I want to share which it might be, if it's nonsense frankly let me know ;)
This is an excerpt from the log:
```
| => cat /Users/oliverjaegle/Library/Application\ Support/Code/logs/20180411T220218/ms-vscode.node-debug_3/debugadapter.txt | grep SmartiAdapter.js
SourceMap: sources: ["meteor://💻app/packages/assistify:ai/server/lib/AiApiAdapter.js","meteor://💻app/packages/assistify:ai/server/lib/KnowledgeAdapterProvider.js","meteor://💻app/packages/assistify:ai/server/lib/SmartiAdapter.js","meteor://💻app/packages/assistify:ai/server/hooks/closeLivechatKnowledgeAdapter.js","meteor://💻app/packages/assistify:ai/server/hooks/sendMessageToKnowledgeAdapter.js","meteor://💻app/packages/assistify:ai/server/methods/SmartiWidgetBackend.js","meteor://💻app/packages/assistify:ai/server/SmartiProxy.js","meteor://💻app/packages/assistify:ai/server/SmartiRouter.js","meteor://💻app/packages/assistify:ai/server/migrations.js","meteor://💻app/packages/assistify:ai/config.js","meteor://💻app/packages/assistify:ai/assistify-ai.js"]
SourceMap: mapping meteor://💻app/packages/assistify:ai/server/lib/SmartiAdapter.js => /Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/lib/SmartiAdapter.js, via sourceMapPathOverrides entry - "meteor://💻app/*": "/Users/oliverjaegle/projects/Rocket.Chat/*"
SourceMaps.scriptParsed: meteor://💻app/packages/assistify_ai.js was just loaded and has mapped sources: ["/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/lib/AiApiAdapter.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/lib/KnowledgeAdapterProvider.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/lib/SmartiAdapter.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/hooks/closeLivechatKnowledgeAdapter.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/hooks/sendMessageToKnowledgeAdapter.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/methods/SmartiWidgetBackend.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/SmartiProxy.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/SmartiRouter.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/server/migrations.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/config.js","/Users/oliverjaegle/projects/Rocket.Chat/packages/assistify:ai/assistify-ai.js"]
```
I noticed the files being properly discovered, but the files are not connected - and then I noticed the funny file-path which doesn't exist on disk: /Users/oliverjaegle/projects/Rocket.Chat/packages/**assistify:ai**/server/lib/AiApiAdapter.js

I figured that the source maps VSCode gets from meteor contain the package **name**.
Sample from the `.js.map`: `{"version":3,"sources":["meteor://💻app/packages/assistify:ai/server/lib/AiApiAdapter.js",`

Our package-names differ from the files on disk. 

Sample package definition: 
```
Package.describe({
	name: 'assistify:ai',
```
Path on disk: `.../assistify-ai/...`

May this cause some trouble?

**Comment by auchenberg** [comment]
What version of Meteor are you using? We had some issues, which were resolved in 1.6, that triggers me ud to write this guide: https://github.com/Microsoft/vscode-recipes/tree/master/meteor

**Comment by mrsimpson** [comment]
yup - verified 🎉 

I renamed the package in the package-definition to that it matches the path on disk to `assistify-ai`.
Now, a breakpoint in a server-side-file of this packages turned red and the debugger stops as expected.

**Comment by roblourens** [comment]
Can you use sourceMapPathOverrides to add a mapping from ...foo:bar... to ...foo-bar... or however it is?

**Comment by mrsimpson** [comment]
Wohoo! You really prepared for a lot of generated-framework-source ~sh*t~ features 🎉 

I added two mappings and it works like a charm:
```
"sourceMapPathOverrides": {
	"meteor://💻app/packages/assistify:*": "${workspaceFolder}/packages/assistify-*",
	"meteor://💻app/packages/rocketchat:*": "${workspaceFolder}/packages/rocketchat-*"
}
```

Thanks a ton, saved me a lot of frustration!

Oliver

P.s.: I'd be delighted if you supported regex in addition to glob with parameters which can be used at the replacing side.

**Comment by roblourens** [comment]
Glad that worked, yeah regex replace would help in this situation, but that level of control isn't often needed.
