### ISSUE TITLE
Simplify generated launch.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-node-debug#185]
This milestone we are looking into simplifing generated launch.json for various extensions Microsoft/vscode#62851
Due to that I decided to create an issue also for node, for discussion and transperency.

Currently we generate the following `launch.json`:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```

We are sometimes smarter and generate a one for ts, or by looking at main and figuring out the program

```
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceFolder}/out/main",
			"outFiles": [
				"${workspaceFolder}/**/*.js"
			]
		}
	]
}
```

I personally like this experience and not sure how much we could further simplify this.
We could potentially add a quick pick to ask launch / attach but imho that would only overcomplicate things.

@auchenberg @weinand @roblourens let me know what you think

**Comment by roblourens** [comment]
Yeah I don't think this can be simplified any more.

**Comment by auchenberg** [comment]
I agree. Our most simple debug story for Node is auto attach from the integrated terminal.
