### ISSUE TITLE
Cannot embed node-debug in other module layouts

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode-node-debug#187]
I'm trying to include node-debug in some other contexts than VSCode (namely in Eclipse Wild Web Developer).
I've built a package.json that contains
```json
{
  ...
  "dependencies": {
    ...
    "node-debug": "file:/path/to/vscode/resources/app/extensions/ms-vscode.node-debug"
  }
}
```
this results of `npm install --no-bin-links --ignore-scripts` are in the following layout
* node_modules
  * node-debug
    * out/...
    * package.json
    * ...
  * source-map
    * dist/...
    * lib/...
    * package.json
    * ...

So far, so good, it matches expectations.

Then, when I try to run node-debug with `node node_modules/node-debug/out/node/nodeDebug.js`, I get a failure: `Error: Cannot find module '../../node_modules/source-map/lib/util.js'`.
If I go to `util.js` and replace the path with `../../../source-map/lib/util.js`, then all seems to start fine.

https://github.com/Microsoft/vscode-node-debug/blob/8b6d99bf915b77d6b859f939c8acd7c059fd48e0/src/node/sourceMaps.ts#L16 should be modified to be more flexible regarding possible layouts.

**Comment by jabby** [comment]
Hello, 

I'm not an expert about nodejs development. As I understand, it's not a best practice to link a file with a path like this.  cf. https://nodejs.org/api/modules.html#modules_require

The good require should be `const util = require('source-map/lib/util.js');` 
I will try this with the Eclipse Wild Web Developer and if it works, I will provide a PR.
