### ISSUE TITLE
Releases do not contain vsix extention

### ISSUE THREAD

**Issue by ibuziuk** [microsoft/vscode-node-debug#191]
The latest stable releases e.g. https://github.com/Microsoft/vscode-node-debug/releases/tag/v1.33.3 do not contain vsix files
Will it be possible to add vsix files to the latest and upcoming releases similar to what is done for other extentions e.g. python https://github.com/Microsoft/vscode-python/releases ?

**Comment by weinand** [comment]
@ibuziuk What do you mean by "The latest stable releases do not contain vsix files"?

**Comment by ibuziuk** [comment]
@weinand releases for the node debug extension do not contain `vsix` files - https://github.com/microsoft/vscode-node-debug/releases/tag/v1.33.3 
Most of the extensions e.g. python contain not only source code, but also `vsix` file e.g. - https://github.com/Microsoft/vscode-python/releases
Will it be possible to add `vsix` to the `vscode-node-debug` extension releases?

**Comment by weinand** [comment]
You can always download the vsix from the marketplace easily: https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug (see the "download extension" link) or build it yourself by running "npm run package" in the vscode-node-debug".

**Comment by ibuziuk** [comment]
@weinand ok, but the GH release process is inconsistent and do not have much value without `vsix`. Most of the popular vs code extensions do have the `vsix` for each release, which makes it really easy to test without a need to build anything manually. Just a handful of examples:

- python https://github.com/Microsoft/vscode-python/releases/
- java - https://github.com/redhat-developer/vscode-java/releases
- go https://github.com/microsoft/vscode-go/releases
- kubernetes-tools - https://github.com/Azure/vscode-kubernetes-tools/releases

@weinand so you still think that the GH release process for `vscode-node-debug` should not be improved?

**Comment by weinand** [comment]
Who uses vscode-node-debug anyway? It is only used for node.js < 8.x.

**Comment by ibuziuk** [comment]
Eclipse Che :-) for legacy support - https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/ms-vscode

**Comment by nickboldt** [comment]
Additionally, Microsoft has said that we're not supposed to link directly to marketplace.visualstudio.com anymore for vscode extensions used outside VS Code itself.

So to use these plugins in Che, we need them published to github releases (or some other place).

See also https://github.com/eclipse/che/issues/14573

**Comment by connor4312** [comment]
We now have a [new debugger](https://github.com/microsoft/vscode-js-debug/). We do not expect to publish m/any more releases of this one.
