### ISSUE TITLE
Error when debugging with Source Maps that use file://

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug#20]
VS Code is unable to resolve a source file for a source map when the entry in the "sources" array of the source map starts with "file://". 

For example, if tsc.js.map contains the source "file:///C:/dev/TypeScript/src/compiler/core.ts", when attempting to debug tsc.js I get an error from VS Code that it cannot load the file "C:/dev/TypeScript/built/local/file/C/dev/TypeScript/src/compiler/core.ts".

**Comment by weinand** [comment]
@rbuckton are you saying that the 'sources' array in the source map contain absolute paths and use file-url syntax? I was not aware that this is actually possible.

**Comment by rbuckton** [comment]
@weinand: The path to a source file can be an absolute url, per this section of the [Source Map Revision 3 Proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k):

> **Resolving Sources**
> If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap (like resolving script src in a html document).
