### ISSUE TITLE
Calculate name for attached processes

### ISSUE THREAD

**Issue by qfox** [microsoft/vscode-node-debug#200]
As I can see name of attached process will be always 'process'.

![image](https://user-images.githubusercontent.com/677518/71251778-520bd480-2334-11ea-86da-2312aa0c7ea4.png)

The code is here https://github.com/microsoft/vscode-node-debug/blob/master/src/node/extension/processPicker.ts#L32 and it doesn't try to find better value for name.

Would be great if it will pick to execution_name. Like `$ ps -c | grep -E -e '^\\s*'$PID' ' | cut -c 26-` or something similar

**Comment by connor4312** [comment]
This is done in our [new debugger](https://github.com/microsoft/vscode-js-debug/)
