### ISSUE TITLE
debug.node.autoAttach=0 results in high CPU on Windows

### ISSUE THREAD

**Issue by teyc** [microsoft/vscode-node-debug#201]
See https://github.com/Microsoft/vscode/issues/60145

autoAttach polls "wmic.exe" with a setTimeout of 1 second, resulting in CPU of an entire core pegging at 100%.

It may be better to use a custom utility instead

**Comment by weinand** [comment]
vscode-node-debug will be soon replaced by vscode-js-debug (which doesn't have the problem.

**Comment by connor4312** [comment]
We've since made the replacement -- auto attach no longer has an overhead aside from listening on a file descriptor.
