### ISSUE TITLE
Auto Attach not working in VsCode when debugging a simple node js application

### ISSUE THREAD

**Issue by Pratyush93exists** [microsoft/vscode-node-debug#206]
Hi I am running my application, index file of which looks something like this :

setTimeOut(()=>{
console.log("HI")
},1000)

I have attached the toggle:Auto Attach mode from the command palatte and is seems to be on after this.

But, when I run the app with the command node --inspect index.js, I see that the execution completes but the debugger is not attached to the process. Can you please help me to triage this?

I have spent a lot of time finding the cause over the web, but nothing seems to help.

I am running this on top of an Ubuntu vm on my local machine.

**Comment by Frisbeetarian** [comment]
Having same issue. All breakpoints are unset. Attaching with Webstorm works fine.

**Comment by connor4312** [comment]
See: https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467. We're reverting to the previous auto attach behavior in the release coming out in a few hours.

Thanks for filing an issue!
