### ISSUE TITLE
SIGKILL sent instead of SIGINT on stop of Debug

### ISSUE THREAD

**Issue by jkoput** [microsoft/vscode-node-debug#212]
Since version 1.47.x, stopping debug session in node no longer sends "SIGINT"; seems to rather send "SIGKILL" which prevents handling of process ending.  Need this to be either changed back or reconfigured so that SIGINT is an option.

Have attempted every version after 1.46.x through current (1.50.1) and multiple versions of node (including 12.19.0 - current stable release) - all with same results.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/630
