### ISSUE TITLE
Auto attach fails when pid is greater than 6 digits.

### ISSUE THREAD

**Issue by istnv** [microsoft/vscode-node-debug#224]
https://github.com/microsoft/vscode-node-debug/blob/f39554d404d3bae9a0cd36274336db7c9b460aaf/src/node/extension/processTree.ts#L126
https://github.com/microsoft/vscode-node-debug/blob/f39554d404d3bae9a0cd36274336db7c9b460aaf/src/node/extension/processTree.ts#L131

Newer Linux releases use a 64 bit process id.
Auto attach works after rebooting the system. 
After the pid numbers exceed 1,000,000 the attach fails.

**Comment by connor4312** [comment]
This extension is no longer updated; the logic in our new debugger ([ref](https://github.com/microsoft/vscode-js-debug/blob/2994e0576d17a54e11132f92945039dd827e0d78/src/ui/processTree/posixProcessTree.ts))  does not have this issue.
