### ISSUE TITLE
Show native code if source not available

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode-node-debug#23]
If a source map is not resolved correctly for a given file when debugging node, VSCode shows "Source is not available."

Is it possible to just show the actual code being executed in these situations?

**Comment by weinand** [comment]
@jamietre this has been fixed in VS Code 0.10.8 (January release).

**Comment by jamietre** [comment]
I had noticed :thumbsup:

**Comment by jamietre** [comment]
I just saw the Feb release, HUGE THANKS for moving the console window to the bottom! Amazing improvement!

Also I think I understand what has happened with source maps. I am not sure if this was the case just for the Jan. release, or if it's different now.

* When using a `debugger` statement, vs code shows the compiled code.
* When using a breakpoint, vs code shows the source code

In the Jan. release, breakpoints weren't actually working (at least for me) so I had been using `debugger` and it didn't occur to me this could be related.

In the version just released, breakpoints are working, and the source code is correctly shown when I use breakpoints in the source, but the compiled code is shown when it breaks on a `debugger` statement.

**Comment by weinand** [comment]
@jamietre breaking on a debugger statement should not behave differently than breaking on a breakpoint. If it does then please file a bug.

**Comment by jamietre** [comment]
Will do.

**Comment by jamietre** [comment]
.. @weinand I am experiencing the problem of "debugger" statements showing the compiled code rather than the source frequently, but it's not consistent. That is, a given "debugger" statement will always show either the correct or incorrect file, but I can't figure out why it happens in some files and not in others. When I created a trivial app to try to reproduce it, I can't. So it must have something specifically to do with the structure of the files in the app I'm working with.

I wanted to just check to be sure I'm still the only one experiencing this before I spend a lot of time trying to create a standalone app that can repro it.

**Comment by weinand** [comment]
@jamietre which version of VS Code are you using?

**Comment by jamietre** [comment]
0.10.8
