### ISSUE TITLE
node-debug module doesn't compare script_name with path correctly on Windows platform

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug#30]
_From @nakosung on December 20, 2015 6:10_

vscode seems to handle 'drive-letter' in both small letter and capital letter, this makes some conflict while dealing with breakpoints.

I would like to PR for this bug fix, but I don't know where to contribute.

_Copied from original issue: Microsoft/vscode#1500_

**Comment by weinand** [comment]
_From @nakosung on December 20, 2015 6:15_

I found vscode-node-debug and opened a PR there.

**Comment by weinand** [comment]
_From @nakosung on December 20, 2015 10:37_

re-opened to discuss here.

**Comment by weinand** [comment]
@nakosung thanks for the PR. While reviewing it I noticed that there is a better way to deal with drive letter casing on windows: instead of setting the breakpoint twice (for upper and lower case), I now use a regular expression for the breakpoint. This makes your PR obsolete.

**Comment by nakosung** [comment]
Oh that will be great. My PR was kind of work-around-hack. :+1:
