### ISSUE TITLE
Attaching to debugger stopped working

### ISSUE THREAD

**Issue by kowsheek** [Microsoft/vscode-node-debug#34]
I have a project based on https://github.com/DaftMonk/generator-angular-fullstack that I was able to debug just fine with the following configuration:

```
{
"version": "0.2.0",
"configurations": [
    {
        "name": "NodeJS Attach",
        "type": "node",
        "request": "attach",
        "port": 5858
    },
    {
        "name": "Chrome Launch",
        "type":"chrome",
        "request": "launch",
        "url": "http://localhost:9000/",
        "sourceMaps": true,
        "webRoot": ".tmp"
    },
    {
        "name": "Chrome Attach",
        "type": "chrome",
        "request": "attach",
        "port": 9222,
        "sourceMaps": true,
        "webRoot": ".tmp"
    }
]
}
```

But since a few releases ago, the attach functionality doesn't work anymore. If I launch with an initial breakpoint the debugger does kick in but doesn't hit any other breakpoints (even if I set them after the initial breakpoint).

Ideally, I should be able to attach to the debugger running on `5858` at any time. Am I missing something here? Happy to share any details needed.

**Comment by weinand** [comment]
This should work in more recent versions of VS Code and node.
