### ISSUE TITLE
Support objects in OutputEvent

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-node-debug#4]
Currently when debugging node, evaluating 'global' gives a nice expandable object, but 'console.log(global)' is a giant string. An OutputEvent should be able to take a variableReference like an evaluate response.

Giving this to you @weinand to investigate and if we want to introduce it give it back gto me so I implement it on the vscode side.
Requested by @roblourens

**Comment by roblourens** [comment]
Should this be tracked in a different repo now?

**Comment by weinand** [comment]
the debug protocol addition is https://github.com/Microsoft/vscode-debugadapter-node/issues/79
