### ISSUE TITLE
How to use this instead of builtin node-debug

### ISSUE THREAD

**Issue by joshgav** [Microsoft/vscode-node-debug#42]
What is the best practice for replacing the builtin `node-debug` extension with this repo? Is it to simply delete/move the builtin one (on Mac: `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/extensions/node-debug`) and symlink this repo in `~/.vscode/extensions`? Thanks!

**Comment by weinand** [comment]
@joshgav there are two ways: 

* if you want to develop node-debug just open the folder it in VS Code and run the launch config 'Run Extension'. This will launch another VS Code window where the builtin node-debug is replaced by your node-debug. In that window you can open a node test project and if you debug it, your debug adapter will be used.

* if you only want to use your node-debug, just do a 'gulp zip' and unzip the resulting `node-debug.zip` from the `upload` directory and then move node-debug folder to your VS Code extension folder: `~/.vscode/extensions/` When running VS Code, the node-debug in the extension folder will override the builtin one.
