### ISSUE TITLE
Sourcemap logic may not capture all inlined sourcemaps

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#45]
You have some code like this:
`if (mapPath.indexOf("data:application/json;base64,") >= 0) {`

but they may not contain that exact string. Here's another vaild inlined sourcemap prefix:
`data:application/json;charset:utf-8;base64,`

So I changed this code to search for the last `,`

**Comment by weinand** [comment]
@roblourens thanks for this info!
Source maps are a pain: everyday I see another format variation...
