### ISSUE TITLE
Firefox Remote Debugging Protocol support

### ISSUE THREAD

**Issue by charlesmilette** [Microsoft/vscode-node-debug#46]
Can this addon also support debugging Javascript with the Firefox browser?

I found some documentation about remote debugging [here](https://wiki.mozilla.org/Remote_Debugging_Protocol)

**Comment by weinand** [comment]
@charlesmilette I assume with 'addon' you mean 'vscode-node-debug', correct?
No, this 'extension' (= addon) only supports VS Code at the moment.

**Comment by charlesmilette** [comment]
Sorry if I wasn't enough precise. I search something like the function for debugging JavaScript with Google Chrome, but with Firefox

**Comment by weinand** [comment]
@charlesmilette vscode-node-debug is a plugin for Visual Studio Code that allows to debug node.js. It is not a browser plugin (neither Chrome nor Firefox or any other browser).

**Comment by charlesmilette** [comment]
I clicked on the CI button on the VS marketplace for [this addon](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) and got brought here... Just a mistake.

**Comment by weinand** [comment]
@charlesmilette strange, the github link on the Marketplace directs me to Microsoft/vscode-**chrome**-debug, not Microsoft/vscode-**node**-debug.

**Comment by roblourens** [comment]
Oops! Fixing :)
