### ISSUE TITLE
Remote debugging not working

### ISSUE THREAD

**Issue by damiantp** [Microsoft/vscode-node-debug#47]
Hi,

I'm testing the new remote debugging funcionality in the VSC January release and it's not working for me.

When adding the new property 'address' it only works for a 'localhost' .But I also have an Ubuntu VirtualBox and I can't make it start debugging. Host machine is Windows 10. I'm using node v5.6.0.

My launch configuration is next:

```
		{
            "request": "attach",
			"name": "Attach to running instance",
			"type": "node",
            "address": "192.168.47.22", // guest machine
            "localRoot": "C:/desarrollo/testing/nodejs/node-express-javascript",
            "remoteRoot": "/var/apps/nodejs/node-express-javascript",
			"port": 5858
		}
```

In host machine I have a shared folder "C:/desarrollo/testing/nodejs" with  the Ubuntu guest machine in order to share the code. I have set up both localRoot and remoteRoot properties accordingly.

I know VS Code is connecting to the remote debug session in guest machine because I run: `node --debug-brk bin/www` and VS Code stops in the first line.

Update: Some more info when testing other options:

I have installed and started node-inspector in the Ubuntu virtualbox and set a breakpoint in the inspector (web page in the host `http://192.168.47.22:8080/?ws=192.168.47.22:8080&port=5858` ). Now the breakpoint is hit in node inspector but (surprinsingly) also in VSCode. So somehow the properties in the launch configuration are ok but, I guess, when setting the breakpoint in VSCode is not working properly.

**Comment by weinand** [comment]
@damiantp does it make a difference if you use a lower case 'c' drive letter for the localRoot attribute?
(I suggest to use the ${workspaceRoot} for 'localRoot').

**Comment by damiantp** [comment]
Hi, 

yes it worked! Now I'm using ${workspaceRoot} as you've suggested.

Thanks.

**Comment by weinand** [comment]
@damiantp So the drive letter case was the problem?

**Comment by damiantp** [comment]
Yes, it was, and using lower case unit name ('c' in this case) worked.

**Comment by weinand** [comment]
@damiantp so this is a bug on my side...
