### ISSUE TITLE
Add release tags?

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode-node-debug#48]
The latest (and only) tag is 0.10.2, but the current release is at 0.10.4

When building vscode from source, manual installation of vscode-node-debug is required for parity with the vscode release version.  The current vscode release uses vscode-node-debug 0.10.4.  If you're trying to replicate the same version that ships in the vscode release build, it's trickier than it needs to be, because:

1) There is no release tag, and
2) Changes that follow the 0.10.4 release continue to use the 0.10.4 version string in the package.json, instead of something like 0.10.5-pre

**Comment by felixfbecker** [comment]
I recommend to use [npm version](https://docs.npmjs.com/cli/version) for new versions. It bumps package.json version, makes a commit and automatically tags it.

**Comment by weinand** [comment]
I've started to add release tags
