### ISSUE TITLE
Breakpoint not hit in TypeScript file, but in JS streamed content instead (remote debugging)

### ISSUE THREAD

**Issue by damiantp** [microsoft/vscode-node-debug#50]
Hi,

I'm testing remote debugging with typescrypt. I'm using the example node-express-typescrypt from the repo.

The issue I have is that when attaching a remote debug session and setting a breakpoint in the .ts file the breakpoint moves up to other line, and when VSCode starts debugging it stops in a .js file (not the real .js file in the folder but a 'content streamed from remote node'). This is the launch config:

```
        {
            "request": "attach",
            "name": "Attach to REMOTE running instance",
            "type": "node",
            "address": "192.168.47.22",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/var/apps/nodejs/node-express-typescript",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/src",
            // Port to attach to, must match port in gulpfile.js
            "port": 5858
        }
```

I've observed that if I attach to a localhost debug session it works (stops in the .ts file), but only when not adding the remoteRoot property. If I add it (although not needed, I guess), the problem arises, it stops in the .js streamed content.

```
        {
            "request": "attach",
            "name": "Attach LOCALHOST to running instance",
            "type": "node",
            "address": "localhost",
            "localRoot": "${workspaceRoot}",
            //"remoteRoot": "${workspaceRoot}", // if uncommented, then it fails (goes to .js streamed content)
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/src",
            // Port to attach to, must match port in gulpfile.js
            "port": 5858
        }   
```

Note: Local machine is Windows 10, Remote machine is Ubuntu 14.04, sharing a folder in windows 10 for the source code.

**Comment by pzien** [comment]
For me fixing paths in source map file itself and using remoteRoot fixed the problem. Although next problem arouse - breakpoint hits in wrong line (correct for generated file).

**Comment by damiantp** [comment]
Not sure if it is the same workaround as @pzien stated, but after revisiting this issue just using an absolute path for the remoteRoot (eg. `C:/testing/nodejs/node-express-typescript/src`) the breakpoint is now hit in the Typescript file. I think it is a minor bug that using `${workspaceRoot}` for remoteRoot it fails.

This was just a complementary test I made (using localhost as remote server) to see why breakpoints were jumping in Typescript when debugging remotely, but using a real remote server (not localhost) breakpoints are still jumping to another line. I'm going to open another issue for this.

The working configuration (with the workaround):

```
		{
            "request": "attach",
			"name": "Attach LOCALHOST to running instance",
			"type": "node",
            "address": "localhost",
            "localRoot": "${workspaceRoot}/src",
            //"remoteRoot": "${workspaceRoot}/src", // if used this way if fails (goes to .js streamed content)
			"remoteRoot": "C:/testing/nodejs/node-express-typescript/src", //using absolute path in remoteRoot as a workaround
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/src",
			// Port to attach to, must match port in gulpfile.js
			"port": 5858
		}   
```

**Comment by weinand** [comment]
@damiantp please make sure that the remote node.js is started with  the `--nolazy` flag. This forces the node runtime to compile the whole file on load which makes breakpoint locations more robust.

**Comment by damiantp** [comment]
@weinand Hi, yes I always start the node app in the remote server with: `node --debug --nolazy file.js` as indicated in the documentation, but it has no effect. I have opened a new issue for this( #75) before I saw this messsage.

**Comment by jasonwilliams** [comment]
Is it related to this? https://github.com/ChromeDevTools/devtools-protocol/issues/103#issuecomment-421183542
