### ISSUE TITLE
Allow to see the entries of ES6 Map and Set

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-node-debug#51]
Currently they only display `map` or `set`, they should work like objects / arrays. For `Set`, basically what you get for `Array.from(set)`.

**Comment by weinand** [comment]
@felixfbecker the v8 debugging protocol doesn't provide that information. I will have to inject code into the debugger for that.

**Comment by felixfbecker** [comment]
Couldn't you execute eval commands to get the contents?

**Comment by weinand** [comment]
@felixfbecker yeah, that's my last resort... The problem with that approach is that I'm getting real objects instead of debug handles. This is a completely different world, e.g. property getters are called transparently etc.

**Comment by weinand** [comment]
@felixfbecker I got this working for Maps...
