### ISSUE TITLE
Move terminal helpers into vscode-debugadapter-node or own npm module

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-node-debug#52]
I just tried to implement `externalConsole` for my PHP debugger and noticed how hard it is cross-platform and with keeping the console open. In the end, I just copied the excellent helper classes from here  into my project. I think a lot of projects would benefit from this. Also, it is nice to have a uniform look for externalConsole (like the title "VS Code debug console").

**Comment by weinand** [comment]
Instead of making the terminal-helpers available as a npm module we've added a 'runInTerminal' request to the debug protocol. In VS Code 1.5 'runInTerminal' supports VS Code's integrated terminal. Support for the external terminal is planned for VS Code 1.6.

**Comment by weinand** [comment]
The 'runInTerminal' request now supports 'integrated' and 'external'. Available in the Insider build.

**Comment by felixfbecker** [comment]
@weinand why a seperate request instead of a launchRequest argument, like it is in launch.json?

**Comment by weinand** [comment]
@felixfbecker it is a reversed request that your debug adapter has to **call** from the implementation of your launchRequest. Please read the release notes that will become available later today.
