### ISSUE TITLE
Breakpoints no longer work for awaited function after 0.10.10 February update

### ISSUE THREAD

**Issue by andrew-w-ross** [Microsoft/vscode-node-debug#54]
I'm not entirely sure if I should raise the ticket here of the vscode repository.
As the title says breakpoints no longer work after the update but if I put a `debugger` statement in then it will correctly show the source code and step through but attempting to add any breakpoints fails.

Edit turns out it's on awaited results that it's having an issue.

**Comment by weinand** [comment]
@andrew-w-ross what version of node are you using? Could you provide a code snippet (or even better a project folder) that shows the issue? Thanks.

**Comment by weinand** [comment]
Closed since no additional information received after 11 days.
