### ISSUE TITLE
 windows docker engine(using virualbox) debug node.js application

### ISSUE THREAD

**Issue by XiSmartElf** [Microsoft/vscode-node-debug#57]
So I use windows so my docker engine runs in virualbox in a Linux environment. This is because docker still not fully support windows env yet. So everything is done through a docker agent in windows communicating with the docker engine inside virtualbox. I know it's hard but still would like to ask if it's possible to debug node application that's running in the virtualbox through VScode? The port mapping is hard to do since there is a virtual machine layer in between.

**Comment by weinand** [comment]
@XiSmartElf VS Code supports the Docker setup on Windows in VirtualBox, but the port mapping you have to do yourself. This is not something VS Code will do.
