### ISSUE TITLE
Program appears to continue executing after pressing stop in the debugger

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug#6]
_From @stevencl on November 16, 2015 15:11_

In a simple node app, I step through a loop in the debugger. Before exiting the loop, I press the stop button
![snip_20151116130725](https://cloud.githubusercontent.com/assets/1704059/11185295/f6af8bbe-8c73-11e5-9a4a-f30d84c14b07.png)
I expect the program to stop executing right at that point but it appears to continue executing due to the fact that the console.log statement is executed (highlighted below) and the value of the string being output looks like the loop continued to execute even after pressing stop:
![snip_20151116150729](https://cloud.githubusercontent.com/assets/1704059/11185303/ff729908-8c73-11e5-8446-f88aa3559d02.png)

_Copied from original issue: Microsoft/vscode#32_

**Comment by weinand** [comment]
_From @jel-massih on November 22, 2015 20:42_

Wouldnt this be an issue with https://github.com/microsoft/vscode-node-debug rather than base vscode?

**Comment by weinand** [comment]
Yes, correct. But there seems to be no way to move this issue over to vscode-node-debug.

**Comment by weinand** [comment]
_From @lukehoban on November 22, 2015 22:40_

@weinand I've used https://github-issue-mover.appspot.com/ successfully for one-off issue moves.

**Comment by weinand** [comment]
@lukehoban great, that seems to work. Thanks!

**Comment by weinand** [comment]
@stevencl good catch! node-debug was disconnecting from node before killing the node process. After a disconnect node continues to run and since killing node is done via a script that needs some time to startup there was enough time for node to finish your program. The fix disconnects from node only in attach mode and kills immediately in launch mode.

**Comment by stevencl** [comment]
Thanks, I can confirm this is fixed in 0.10.4

**Comment by weinand** [comment]
@stevencl thanks, but no need to add a comment, just add the label "verified"

**Comment by stevencl** [comment]
Thanks, I was wondering about that...
