### ISSUE TITLE
launch.json settings to enable debugging into ripple emulate

### ISSUE THREAD

**Issue by myusrn** [Microsoft/vscode-node-debug#63]
i'm looking to use vscode to facilitate debugging into "ripple emulate" startup behavior for "npm install ripple-emulator" package in order to look at possible resolutions to this [https://github.com/ripple-emulator/ripple/issues/16](https://github.com/ripple-emulator/ripple/issues/16) feature request.

i'm stuck figuring out what to use in .vscode/launch.json node.js debugging settings, presumably for "program" and "args" properties, in order to make that work.   I've tried "program": "${workspaceRoot}/lib/index" + "args": [ "emulate", "--nobrowser" ] but vscode debugger launch doesn't like that.

any pointers on how to get going with this npm package debugging story so i can understand what area of its sources does incoming arguments processing and browser launching in order to create a PR that will add the "--nobrowser" option?

**Comment by weinand** [comment]
@myusrn node-debug creates the command from the individual attributes of the launch config like this:

```
<runtimeExecutable> <runtimeArgs> --debug-brk=<port> <program> <args>
```

If the `runtimeExecutable` is not specified, it is set to 'node'.

So you can specify an arbitrary program for `runtimeExecutable` as long as it can deal with all the other arguments.
