### ISSUE TITLE
Improve node.js version detection for Electron

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-node-debug#65]
Related: https://github.com/Microsoft/vscode-node-debug/issues/64

Instead of hardcoding the version of node.js when detecting Electron, a better solution should be implemented. I would ask Electron people to return the version number properly but also implement a fallback solution where you check the V8 version they return and correlate that to the node.js version of their release.

Since Electron is not updating node.js so often, that is probably a good solution for now.

**Comment by weinand** [comment]
Obsolete since node-debug only covers "legacy" protocol which is no longer used by Electron.
