### ISSUE TITLE
Breakpoints not triggered visually in v 1.0.0

### ISSUE THREAD

**Issue by pierznj** [Microsoft/vscode-node-debug#67]
I'm running version 1.0.0 and am having issues with node debugging not working properly. The code does seem to stop at any breakpoints I set, but the line is not highlighted  and there is no information in the debug pane. I have seen it work, but it stopped and now I can't get it to work again, even after restarting VS Code completely.

**Comment by egamma** [comment]
// @weinand

**Comment by isidorn** [comment]
Can you please give us reproducable steps so we try to investigate the issue you are seeing. Can you create a small repository on github for which we can also see the issue you are experienceing.

For more details on setting up debug please check these [docs](https://code.visualstudio.com/docs/editor/debugging)

**Comment by mattflix** [comment]
This appears to be a debugging incompatibility with Node 6.x.

The same problem started happening to me when I upgraded from Node 5.11.1 to Node 6.1.0.  When I downgraded back, proper breakpoint behavior was restored.  I am running on Mac OS X.

I also noticed a new (error?) message appearing in the console with each debug launch after upgrading to Node 6.1.0:
```
node --debug-brk=46641 --nolazy ./index.js
Debugger listening on port 46641
(node:63257) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```
This new message also went away when I downgraded back to Node 5.11.1.

**Comment by pierznj** [comment]
Thanks mattflix. I'll try that. For the record I haven't been able to find a set of steps that reliably produces this bug. It's intermittent but frequent.

**Comment by weinand** [comment]
@pierznj are you using VS Code 1.0 with node v6?
Node v6 seems to have a problem returning correct callstacks for some callbacks. Please try the upcoming VS Code 1.1 which has a workaround for that problem.

**Comment by crazyquark** [comment]
I tried a dev build of VS Code 1.1 (from github) + vscode-node-debug extension(also from github) and the issue seems to be fixed(because of use of Node v5.10).

**Comment by mattflix** [comment]
@crazyquark I'm confused by your "because of use of Node v5.10" comment. Are you saying breakpoints work with Node 6.x now in VS Code 1.1?

**Comment by weinand** [comment]
@crazyquark breakpoints should work with Node 6.x in VS Code 1.1 if the program was launched via VS Code or if VS Code attaches to a program that was launched outside of VS Code with the --debug-brk flag.

**Comment by mattflix** [comment]
@weinand wrt VSC 1.1 and Node 6.x, what's the issue with --debug vs --debug-brk (i.e., why doesn't --debug work).  Will the issue eventually be fixed?

**Comment by weinand** [comment]
@mattflix VS Code injects code into node.js to work around slowness issues with large data structures. For reasons we do not yet understand this injected code fixes the issue in node v6 that requesting the call stack results in an "Internal error: illegal access" error.
VS Code injects the code with an 'eval' request.
The injected code uses a 'require(...)' which is only available if node is stopped. This is only the case if node is started wit `--debug-brk`.

We hope that the node v6 issue will be eventually fixed.

**Comment by pierznj** [comment]
Actually (hate to spoil the party) but seems I'm using node 5.2. My code is doing a lot of traversing of large arrays (up to 10000 elements). Not sure if that is a factor. Sometimes execution stops without a visible breakpoint and hitting play then highlights the line. Frequently I get timeout messages about node not having responded in a timely manner. Hope maybe 1.1 might fix my issues too?

**Comment by weinand** [comment]
We fixed several issues in this area for VS Code 1.2.0. Please give it a try and create a new issues if you still see issues with it.
