### ISSUE TITLE
Adapter should check if node runtime supports extending the debugger before injecting extension scripts

### ISSUE THREAD

**Issue by agarwal-sandeep** [Microsoft/vscode-node-debug#71]
Before injecting the debugger extension scripts adapter should check if node runtime supports extending the debugger. This will allow other node runtime which doesn't support the internal debugger logic of V8 (mirror, DebugCommandProcessor etc.) but supports V8 Debugging Protocol to be debuggable using VSCode.

nodeDebug.ts release [0.10.10](https://github.com/Microsoft/vscode-node-debug/blob/release/0.10.10/src/node/nodeDebug.ts#L675) used to have the check but that was removed.

Having the check will allow [node-chakracore](https://github.com/nodejs/node-chakracore) to use the new debugging APIs https://github.com/Microsoft/ChakraCore/commit/78c7913bd8a46d70fdfbd15a0c296e16de72604d and a [shim](https://github.com/agarwal-sandeep/node-chakracore/blob/debugging/deps/chakrashim/lib/chakra_debug.js) to implement V8 debugging protocol.

**Comment by weinand** [comment]
@agarwal-sandeep VS Code 1.2 does a version check (based on the version number found in the `Embedding-Host` attribute in the first V8 protocol header) before injecting code.
But since we've extended the range of supported versions of the node runtime, it could be that the chakra runtime is no longer 'magically' excluded. Is there another header attribute that we can use to identify chakra?

The header of the latest node looks like this:
```
V8-Version: 5.0.71.52
Protocol-Version: 1
Embedding-Host: node v6.2.1
Content-Length: 0
```

And this is the header of the Electron:
```
V8-Version: 4.9.385.28
Protocol-Version: 1
Embedding-Host: Electron
Content-Length: 0
```
How does the header look like for Chakra?

Another question: If the version check from above does not exclude Chakra, what actually happens if we inject code into Chakra? Our code expects that the 'evaluate' call with the code to inject should fail.
But we silently ignore the error and continue the debug session without using the injected code.

Does this not work for Chakra?

**Comment by agarwal-sandeep** [comment]
Thanks @Weinand,
The header for current node-chakracore master is
```comment
V8-Version: undefined
Protocol-Version: 1
Embedding-Host: node v7.0.0-pre
Content-Length: 0
```
Since the JavaScript engine is ChakraCore v8 version is undefined.

In node-chakracore `process.jsEngine` is defined as `chakracore` if compiled with chakracore or `v8` if compiled with v8. I can include `Js-Engine` in header for node-chakracore but it won't be present in official node (v8) so safe check is to check for `V8-Version` and see it is not undefined before injecting extension code.

For injected script evaluate request, node-chakracore returns json as below but later on node-chakracore dies as it can't handle command `vscode_backtrace`

```json
{
  "seq" : 1,
  "request_seq" : 2,
  "type" : "response",
  "command" : "evaluate",
  "success" : true,
  "refs" : [],
  "running" : false,
  "body" : {
    "name" : "<Injected script source>",
    "type" : "object",
    "className" : "Error",
    "display" : "'LookupMirror' is undefined",
    "propertyAttributes" : 1,
    "handle" : 11,
    "value" : "'LookupMirror' is undefined",
    "text" : "'LookupMirror' is undefined",
    "properties" : [{
        "name" : "__proto__",
        "propertyType" : 0,
        "ref" : 12
      }, {
        "name" : "message",
        "propertyType" : 0,
        "ref" : 13
      }, {
        "name" : "description",
        "propertyType" : 0,
        "ref" : 14
      }, {
        "name" : "number",
        "propertyType" : 0,
        "ref" : 15
      }, {
        "name" : "stack",
        "propertyType" : 0,
        "ref" : 16
      }
    ]
  }
}
```
@aruneshchandra - FYI

**Comment by weinand** [comment]
@agarwal-sandeep thanks, that helps a lot.

Interestingly node.js versions that have a problem with the injected code return a `"success" : false` which VS Code uses to detect whether the injections works.

Chakra returns `"success" : true` but returns an error in the result object.

I'm not sure what the correct solution is, but I already know that VS Code's watch expressions are relying on the `success` attribute when showing that a watch expression is undefined. So there seems to be a discrepancy between node and Chakra.

In VS Code I will use the `undefined` value of the `V8-Version` and the error object returned from the evaluate request as an indication that code injection should not be used or didn't work.

**Comment by agarwal-sandeep** [comment]
@weinand Thanks for fixing. Do you know when this will make to VSCode?

**Comment by weinand** [comment]
@agarwal-sandeep the fix will be in the next VS Code Insider build of this night.
