### ISSUE TITLE
UI support for TimeTravel Debugging for Node

### ISSUE THREAD

**Issue by aruneshchandra** [Microsoft/vscode-node-debug#72]
[Node-ChakraCore](https://github.com/nodejs/node-chakracore/) has been working on bringing TTD to Node.js developers with the idea to surface this feature using VSCode. 

Hitting a breakpoint and stepping forward is a familiar experience, but TTD allows developers to step back after hitting the breakpoint. For this new UI affordance needs to be built in VSCode, for example a "StepBack" button on the debug bar. Ideally this new button could be conditional based on a capability detection of the underlying Node platform.

Adding this support in VSCode will help us bring this innovation to the node developers.

**Comment by roblourens** [comment]
If it's useful at all, this was prototyped in https://github.com/roblourens/vscode/commits/stepback and https://github.com/roblourens/vscode-node-debug/commits/stepback

**Comment by weinand** [comment]
@isidorn I've added protocol support for this (and I will enable it in mock-debug).
Please add UiI support for this.

**Comment by isidorn** [comment]
Moved here https://github.com/Microsoft/vscode/issues/7652 since it is easier for me to track issues in our main vscode repo
