### ISSUE TITLE
Can't debug symlinked scripts (as in with 'npm link')

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#73]
I'm developing my debug adapter in two projects at once. In one of them I use 'npm link' to create a symlink from the development folder to the node_modules folder of the extension project that depends on it. But I can't debug it with node without a workaround.

I think the problem is that vscode doesn't resolve the symlink, so when I set a breakpoint in it, it reports that it's in 'c:\extensionproject\node_modules\dependency\file.js' or wherever, but node is reporting that the file is 'c:\dependency\file.js'. Does that make sense?

My workaround is to add a debugger statement. When I break there, vscode has opened a second copy of that script where the symlink path has been resolved to its actual location, and breakpoints in that file work. But it's an annoying workaround, and would be even more complicated to make sourcemaps work.

**Comment by roblourens** [comment]
I thought filesGlob might help, but I still can't set a bp in the linked dir. But, I can use attach and localRoot/remoteRoot. Works perfectly.

**Comment by weinand** [comment]
@roblourens in hindsight your results make sense: a linked dir is not just another folder with more generated code (which would be covered by a `outFiles` glob pattern). Instead it is a location which is seen by the node runtime with a different path than by VS Code which results in non-matching breakpoint locations (which can be addressed by `localRoot/remoteRoot`). 
It would probably make sense to add support for multiple localRoot/remoteRoot pairs...

**Comment by rgilling** [comment]
No worries. Will work with the workaround. I did add a debugger statement and that works well enough. The symlinks cause more issues than they solve with npm link! Would `--preserve-symlinks` help? That was a node option I was using to try to get Mocha working one time with a parent project's config.

**Comment by roblourens** [comment]
Whoa! That works for me!

```
"runtimeArgs": [
    "--preserve-symlinks"
],
```

Looks like that option was added after I filed this issue, and I never looked for a better way. Thanks for the tip!

**Comment by weinand** [comment]
@rgilling thanks for the tip. I will close this issue now.

**Comment by robertjd** [comment]
@roblourens that's exciting!  I'm trying to add the same runtimeArgs to my launch.json, but I'm not seeing the success you saw.  Is there any other configuration needed for this?  I believe my situation is the same as yours:  I have two npm packages open in two different vscode windows,  one is npm linked to the other, and I want the debugger to know about break points that I set in both.  Thanks!

**Comment by TimNZ** [comment]
Why isn't --preserve-symlinks the default?

What is the scenario where I have linked a module and don't want to follow it?

**Comment by auchenberg** [comment]
@weinand @roblourens Any downsides of making `--preserve-symlinks` a default runtimeArg?

**Comment by weinand** [comment]
Why isn't `--preserve-symlinks` not a default for node.js itself?

It would be confusing for users if we pass a non-default option to node.js only while debugging.
This could result in different runtime behaviour when debugging.

**Comment by auchenberg** [comment]
That is a good point. Reading the docs it looks like it can consequences for native modules. https://nodejs.org/api/cli.html#cli_preserve_symlinks

**Comment by TimNZ** [comment]
Ugly.  Thanks for checking it out.

I guess what a sane default is depends on which would win in being a more common case - linked modules with no native modules, or linked modules with native modules, and debugging.

Status quo is most probably easiest then.
