### ISSUE TITLE
No callstack when breaking on 'debugger' statement in eval'd script

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#74]
`eval('debugger')`

Pauses, but the call stack window says "No call stack available (Cannot read property 'indexOf' of undefined)".

You might not care about this scenario for Node, I only noticed it because I was looking at eval script debugging for Chrome, where it's more common.

**Comment by weinand** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7481
@roblourens this had been fixed last week. It is already available in the Insider.
