### ISSUE TITLE
Breakpoints "jump" in Typescript with remote debugging

### ISSUE THREAD

**Issue by damiantp** [Microsoft/vscode-node-debug#75]
I'm testing how to use typescript and remote dubugging. The problem I  have is that when setting breakpoints, as soon the debugger is attached, they jump to a previous lines (a few lines back). The debugger is still stopping at the original breakpoint position, but sometimes it can be a bit misleading when using several breakpoints.

Here a screenshot showing the case. Breakpoint is in line 10, but it moved to line 6. In this case I double-clicked line number 10 so at least a "unverified breakpoint" is added in gray color.

![captura de pantalla 2016-06-14 10 57 51](https://cloud.githubusercontent.com/assets/17238247/16037106/50e2e6ca-321f-11e6-9bb9-dc992a4f1150.png)

The debugger is started in the remote server with --nolazy but it has no effect.

When using "launch" mode locally or even using "attach" in remote debugging but with "localhost" as remote address it is working fine.

In my case remote server is Ubuntu 14.04 in a Virtual Machine. Host server is Windows10. Files are shared using a shared folder between Windows and Linux. Have also checked that using Windows7 as a remote server is also failing.

Launch config is next:

```
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "192.168.1.22",
            "restart": true,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/var/apps/nodejs/rtc"
        }
```

**Comment by damiantp** [comment]
I've been testing this again but no luck, the only conclusion I have is that when setting up a remote launch breakpoints in TS files move to the corresponding positions in the JS file.

@weinand Do you have any clue why this is happening? I have setup a repo in case you want to test it or have a look: https://github.com/damiantp/vcode-nodejs-testdebug.git

**Comment by delfinof** [comment]
It looks like the same as this (look at the uploaded image with the red "arrow" ):
     https://github.com/Microsoft/vscode/issues/2472

**Comment by weinand** [comment]
This has been fixed with this commit: https://github.com/Microsoft/vscode-node-debug/commit/652d3e1593e043c0f3f83b4aa36c185aad22c31a
The fix is already available in the Insider build.
