### ISSUE TITLE
Debugging hangs on language server

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode-node-debug#76]
Hello!
I hope this is the right repository where to put this issue.

I am basically trying to program a language extension (with client and server code).

I followed the instructions on the tutorial, and everything looks working correctly.
However whenever I put a breakpoint on the server code and I try to go to the next line, it hangs and this is the only message I get.

![image](https://cloud.githubusercontent.com/assets/1416224/16158264/cfcdb934-34bc-11e6-967f-50c52e070bcd.png)

Furthermore, it looks like the debugger isn't able to inspect non `typescript` objects; I was wondering wether there's a javascript starting template I can use; I am not really interested in using Typescript.

I am using latest May release, and I tried with both node 4 and 6

Is there any suggestion, or something to look into?

**Comment by XVincentX** [comment]
By the way, it looks like the bug was solved updating VSCode to June release.

**Comment by weinand** [comment]
@XVincentX thanks for letting me know.
