### ISSUE TITLE
Adding step back capability to VSCode node-debug adapter for TTD

### ISSUE THREAD

**Issue by agarwal-sandeep** [Microsoft/vscode-node-debug#77]
Add stepaction _back_ to _continue_ command for supporting stepback functionality in TTD. Please refer to issue https://github.com/Microsoft/vscode/issues/7652#issuecomment-226879654 and https://github.com/Microsoft/vscode-node-debug/issues/72 for more details

**Comment by weinand** [comment]
node-debug now implements the `stepBack` request (https://github.com/Microsoft/vscode-node-debug/commit/5dc80e6339c4f5682d2054e8470ed79104c4bb30) and returns the `supportsStepBack` capability from the `launch` and `attach` requests (https://github.com/Microsoft/vscode-node-debug/commit/12531944f6303458059763fbe2a8c2ef815e8932).
