### ISSUE TITLE
maps don't show in variables in insiders build

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-node-debug#79]
![image](https://cloud.githubusercontent.com/assets/1018196/16433071/31e92e72-3d3d-11e6-9933-9ef83bd23f57.png)

Should display a key value tree.

**Comment by weinand** [comment]
Maps do work for me in node 5.11.0:
![2016-06-29_23-29-15](https://cloud.githubusercontent.com/assets/1898161/16469450/50d844de-3e51-11e6-8ae3-339a6b1e63b6.png)

What version of node are you using?

**Comment by nojvek** [comment]
node 6.2.1

**Comment by weinand** [comment]
@nojvek this is on Windows? Do you have a small snippet that I can use to reproduce this?

**Comment by weinand** [comment]
Since I cannot reproduce, I can't investigate without requested info.

**Comment by nojvek** [comment]
Hi Andre,

No problem. I will try again with latest node and get back to you again.

Regards.
