### ISSUE TITLE
Upcoming fs.realPath() returns real casing of path

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-node-debug#80]
FYI it seems that the new node.js 6 fs.realPath implementation uses a native method from lib uv and I verified that this returns the proper casing of a path on Mac and Windows!

So it seems the workaround for having to go through all parent directories to find their proper casing is no longer needed.

Refs: https://github.com/libuv/libuv/blob/v1.x/ChangeLog#L311

**Comment by weinand** [comment]
@bpasero great, thanks for letting me know!

**Comment by orangemocha** [comment]
What is your dependency on fs.realPath? We are considering some changes in core that would normalize the keys of the module loader cache (`require.cache`) to lowercase on Windows.

**Comment by weinand** [comment]
@orangemocha node-debug warns the user if he has specified a file path in a configuration file that doesn't uses the same character case as the file on disk.
In that case node.js breakpoints are not hit even on a case insensitive file system.
Currently we have our own implementation of fs.realPath() that walks the folder hierarchy.

**Comment by orangemocha** [comment]
Ok, it doesn't seem like the require.cache changes would affect you then.

FYI, we are also trying to restore fs.realPath old behavior when it comes to network shares mapped to drive letters: https://github.com/nodejs/node/pull/7559#issue-164058135
