### ISSUE TITLE
Avoide usage of additional_context when evaluating for non V8 engines

### ISSUE THREAD

**Issue by agarwal-sandeep** [Microsoft/vscode-node-debug#81]
In vscode-node-debug adapter when creating

[ArrayVariable](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L2383)
SetVariable/SetElements
MapVariable/MapElements
StringVariable
SetPropertyValue

The adapter calls evaluate with [additional_context](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L2399). Current implementation of ChakraCore debugging doesn’t provide such functionality of passing additional context for evaluation. It seems [CrDP](https://developer.chrome.com/devtools/docs/debugger-protocol) [evaluateOnCallFrame](https://chromedevtools.github.io/debugger-protocol-viewer/1-1/Debugger/#method-evaluateOnCallFrame) doesn’t support such functional and since V8 debugger protocol is obsolete and no longer maintained it won’t be a good choice for Chakra to provide such functionality. 

Please consider not using additional_context for non V8 based providers.

**Comment by weinand** [comment]
The fix cripples node-debug in the following way:
- no content is shown for 'set' and 'map' data structures
- the full contents of long strings (> 90 chars) is not available
- array size is not available and no paging for arrays
- 'set value' not available for object properties or array slots. 

The fix will be available in the next insiders build (Monday).
