### ISSUE TITLE
Sourcemap resolution not working for sourcemaps in node_modules folders.

### ISSUE THREAD

**Issue by shoerob** [Microsoft/vscode-node-debug#82]
I have a few node_modules I am including in a main project that include .js, .d.ts, .js.map, and .ts files. The reason for this is that I'd like to be able to debug the main project, as well as the modules which it heavily depends on via npm linking the modules during development. The structure of the fully built project is as follows:

project/src/index.ts
project/lib/index.d.ts
project/lib/index.js
project/lib/index.js.map
project/node_modules/mymodule/src/someclass.ts
project/node_modules/mymodule/lib/someclass.d.ts
project/node_modules/mymodule/lib/someclass.js
project/node_modules/mymodule/lib/someclass.js.map

Note that "project/src/index.ts" imports "someclass" in the following way:
import { someclass } from 'mymodule/lib/someclass';

My launch.json has the following configuration:

``` json
{
    "name": "Launch",
    "trace": "all",
    "type": "node",
    "request": "launch",
    "program": "${workspaceRoot}/src/index.ts",
    "stopOnEntry": false,
    "args": [],
    "cwd": "${workspaceRoot}",
    "preLaunchTask": "build",
    "runtimeExecutable": null,
    "runtimeArgs": [
        "--nolazy"
    ],
    "env": {
        "NODE_ENV": "development"
    },
    "externalConsole": true,
    "sourceMaps": true,
    "outDir": "${workspaceRoot}/lib"
},
```

When launching the application, any breakpoints I set in "project/src/index.ts" are successfully detected and hit. Any breakpoints I set in "project/node_modules/mymodule/src/someclass.ts" are noted in VSCode as "breakpoint ignored because generated code not found". However, when I set a breakpoint in "project/node_modules/mymodule/lib/someclass.js" (the javascript file), the breakpoint is set, and when it is hit, the corresponding .ts file is displayed in VSCode.

In looking at the source code for vscode-node-debug, it looks like sourcemaps are resolve in one of the following ways when a breakpoint is set in a .ts file (please correct me if I am wrong):
- try to find a sourcemap relative to the .ts file
- try to find an already loaded sourcemap by matching the .ts file to the sources array.
- try to find a sourcemap in the outDir specified in the configuration.

Based on this, I can understand why the sourcemap for "someclass.ts" does not get resolved. I can also understand why adding the breakpoint to "someclass.js" causes the sourcemap to resolve successfully. This is because the .js file contains a sourceMappingURL which points to the correct location, and removes the guesswork.

That being said, I am wondering if this falls under the category of bug or feature request. Should I be able to debug typescript w/sourcemaps in the node_modules subfolders by adding breakpoints to those typescript files? Or - should I be using a different project configuration altogether to make debugging work properly? I don't think my project setup is that unreasonable given the environment, but I am open to suggestions.

One way to fix this would be to specify multiple directories for "outDir" instead of restricting it to just one. In doing so, vscode-node-debug would be able to search in multiple custom locations for sourcemaps instead of just the main project compilation folder.

Please let me know if you need me to explain this in any more detail.

**Comment by cesarvarela** [comment]
Any update about this?

I'm using mutiple glob patterns in  the `outFiles` section of lauch.json to no avail

**Comment by jamietre** [comment]
Just started having this problem too

In `node_modules/some-module` I have a structure

    node_modules/some-module
       src/x.ts
       src/subfolder/y.ts
       x.js
       x.map.js
       subfolder/y.js
       subfolder/y.map.js

each file `xxx.js` ends with: 

    //# sourceMappingURL=bind-all.js.map

bind-all.js.map:

    {"version":3,"sources":["../src/objects/bind-all.ts"],"names":[],"mappings":" ... "file":"bind-all.js"}

.. with a valid relative path to the source file under `src` showing source map. It always just shows the `js` code.

Doesn't work even if I embed the source in the map file. It seems like the map is being completely ignored.

**Comment by sandyplace** [comment]
Having the exact same issue. Is there best practices for re-using your existing source code libraries developed internally with new projects as described by @shoerob? He articulates exactly what we have setup as well. Is there some other way to set this up to get source debugging and break points in your common shared libraries?

**Comment by weinand** [comment]
I've no problems with source maps in npm modules. The following screenshot shows VS Code's node debugger being debugged by itself:

![2017-03-31_09-24-50](https://cloud.githubusercontent.com/assets/1898161/24540545/07c76a74-15f4-11e7-966c-4dfde70c2f69.png)

Here `loggingDebugSession.ts` and `protocol.ts` are coming from the npm module [vscode-debugadapter](https://github.com/Microsoft/vscode-debugadapter-node/tree/master/adapter).

For the npm modules I let the TypeScript transpiler create inlined source maps with inline source:
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/adapter/src/tsconfig.json

In the screenshot you can see editor header that VS Code loads the inlined source from the sourcemap.

In the project that uses the npm module, I do not have to add anything node module related to the `outFiles` attribute because inlined source maps with inlined source are self contained.

You can find the node-debug project here:
node-debug https://github.com/Microsoft/vscode-node-debug

**Comment by weinand** [comment]
@jamietre did you add the location of the generated JavaScript in your node modules as an `outFiles` glob pattern?

Something like:
```json
"outFiles": [ "${workspaceRoot}/node_modules/**/*.js" ]
```
If you know that only a few of the modules use source maps you can improve lookup performance by restricting the glob pattern only to specific modules:
```json
"outFiles": [ "${workspaceRoot}/node_modules/{module_a,module_b}/**/*.js" ]
```
