### ISSUE TITLE
Nodejs debugger does not find my local files/module 

### ISSUE THREAD

**Issue by mirmajeed1** [Microsoft/vscode-node-debug#83]
If I run my node.js project with npm it runs fine but if I try to debug it using visual studio code the debugger throws errors that it cannot find my local modules. I have the following require statement
service = require('lib/service-call');

**Comment by weinand** [comment]
@mirmajeed1 which versions of VS Code and node.js are you using?

**Comment by weinand** [comment]
No reply. closing.
