### ISSUE TITLE
"<data error: Internal error: illegal access>"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#87]
![image](https://cloud.githubusercontent.com/assets/323878/18221710/5bcad5fa-7137-11e6-8e31-ac0100295d7d.png)

I see this for any `vscode.window` function. All other functions show up fine. In 1.4 and 1.5-insider.

**Comment by Capyvara** [comment]
FYI I'm also having this error by attaching to a node instance. "Solved" by upgrading node to the v6.3.0 which accepts the --inspect flag instead (in attach select node2 type and port 9229

**Comment by weinand** [comment]
should no longer occur.
