### ISSUE TITLE
Debugging extensions based on the Javascript generator works, those on Typescript timeout

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug#9]
_From @jimthedev on November 19, 2015 21:52_

I think I've outlined this pretty well here:

http://stackoverflow.com/questions/33811221/visual-studio-code-extension-host-timeout-during-debugging

Basically the problem is that when I actually try to debug the extension, those based on Typescript just result in timeouts of both sides of the debugging workflow.

In Javascript everything seems to work properly. I'm not sure if this is just a race condition based on the fact that the typescript must be compiled and thus pushes it outside the 3000ms timeout that Code seems to be willing to wait.

_Copied from original issue: Microsoft/vscode-generator-code#15_

**Comment by weinand** [comment]
_From @bpasero on November 20, 2015 7:19_

@isidorn please chime in

**Comment by weinand** [comment]
_From @isidorn on November 20, 2015 9:31_

In 0.10.1 we actually do not wait for the gulp task to [finish](https://github.com/Microsoft/vscode/issues/170) before starting debug, so that should not be the cause of the timeout.
I tried your scenario and it works for me.

Forwarding to @weinand

**Comment by weinand** [comment]
_From @bpasero on November 23, 2015 8:53_

Please move this over to https://github.com/Microsoft/vscode/

**Comment by jimthedev** [comment]
I'd be happy to provide more info on this if needed

**Comment by weinand** [comment]
@jimthedev I've just tried to reproduce your problem on OS X 10.10.5 with the latest version of the yeoman generator and VS Code 0.10.1. But I couldn't (and there are no other reports of this problem).
So most likely this is not a fundamental problem but something specific with your system or setup.

Since you are debugging an extension from within VS Code, it doesn't matter what version of node you have installed, because VS Code (or better Electron) comes with its own version and that one is used for debugging your extension as well.

When you press F5 the launch configuration builds (compiles) the TypeScript source into the 'out' folder. Can you please make sure that your 'out' folder looks like the one from this screenshot:

![2015-11-23 21-51-14](https://cloud.githubusercontent.com/assets/1898161/11349433/8c8034c8-922c-11e5-9612-30ab9592bb23.png)

**Comment by Alphapage** [comment]
They can't reproduce the bug at Microsoft because they are working on supercomputer or surface pro 8 ;-)

To solve the same problem, I changed line 203 in "C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node-debug\out\node\nodeDebug.js" to 
```
_this._attach(response, port, 30000); // 3000 before
```
This is only my workaround on vscode 0.10.3, and I patched Linux and osx too.

Hope this helps.

**Comment by weinand** [comment]
The default timeout for attach has been changed to 10000. If this is not enough you can increase this value by setting the 'timeout' attribute in an attach launch config.
