### ISSUE TITLE
Numerical props in variables pane maybe should not be wrapped in [ ]

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#92]
![image](https://cloud.githubusercontent.com/assets/323878/18562138/d36f17ec-7b82-11e6-90a0-2415582a600a.png)
I'm not really worried about this kind of case, but just showing why it feels kind of arbitrary since in JS there isn't really a difference between an indexed property of an array, and a property of an object that just happens to only have numbers in it. Probably won't format it this way in Microsoft/vscode-node-cdp-debug but want to file this issue for discussion.

**Comment by weinand** [comment]
I've stopped wrapping numerical props in square brackets.
