### ISSUE TITLE
Debugger pausing on Exception but not telling me what the Exception is

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode-node-debug#94]
I'm debugging an extension. I have the following (JS file):

```
let myFunction = () => {

  return new Promise((resolve, reject)=> {

    if (someArray.length === 0) {

      vscode.window.showInformationMessage('There was a problem');
      reject("There was a problem");  // <-- Debugger is pausing on this line, but not showing an Exception

    } else {

      // .... do some other stuff

      resolve("Success!!");

    }

  });   

}

let myCommand = () => {

  myFunction()
  .then((value) => {
    console.log(value);
  }).reject((err)=> {
    console.error(err);
  });

}
```

So with the above code, when I attempt to reject a value in that Promise, the debugger always pauses there saying there is an exception. But I don't see any actual exception specified anywhere in the debug sidebar or debug console. Is there something about the debugger that I'm not understand. And I have no clue why the reject command is pausing. If I continue the debugging, the command finishes as expected without error. So I don't understand that either.

![screenshot 121](https://cloud.githubusercontent.com/assets/87356/18612919/6e324632-7d27-11e6-84ac-457a97992850.jpg)

**Comment by Jakobud** [comment]
Okay I figured out why I was getting an exception. Something to do with fact that I was trying to do a syncronous rejection. This fixed it:

```
vscode.window.showInformationWindow(...)
  .then(()=>{ reject(...); });
```

But I'm still confused on why the debugger will stop for an exception but not actually tell you what the exception is.

**Comment by Jakobud** [comment]
Also I found this:

http://stackoverflow.com/questions/39063281/typescript-promise-rejecting-and-vscode-debugger-behavior

So is this a bug that VSCode has issues with synchronous Promise rejections?

**Comment by weinand** [comment]
Please see https://github.com/Microsoft/vscode/issues/1746 for an analysis and possible workarounds.
