### ISSUE TITLE
Locals pane is empty when an ArrayBuffer is in scope

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#95]
`const buffer = new ArrayBuffer(8);` - have this code then step past it, and the locals pane will be blank. It maybe looks like an array but doesn't quite act like it.

**Comment by weinand** [comment]
With the fix I'm no longer choking on an ArrayBuffer but the `byteLength` attribute isn't shown because it is not available through the v8 protocol.
