### ISSUE TITLE
error: base path missing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#96]
I see this error in the callstack when I debug my simple test app. I don't think it does anything unusual...

![image](https://cloud.githubusercontent.com/assets/323878/18842830/330ba3d2-83cb-11e6-9874-ab22fedb85de.png)

**Comment by roblourens** [comment]
Fix might be to pass `pathToGenerated` at https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/sourceMaps.ts#L248?

**Comment by isidorn** [comment]
This error is not coming from the vscode side - I believe it is coming from the node debug adapter

**Comment by roblourens** [comment]
Oh I see why I don't see this in other apps, this only reproes when the script isn't loaded by `outFiles`/`outDir`. I think it loads sourcemaps later and tries to use them for the stacktrace but something isn't working. I could fix it but I don't think it's high priority.

**Comment by roblourens** [comment]
I take that back, this also will show up when you debug node_modules with sourcemaps. I'll fix it.

**Comment by roblourens** [comment]
I published with this fix and updated the pointer in vscode.

**Comment by isidorn** [comment]
Awesome - thanks! While @weinand is on vacation we should look into node debug issues and address the ones which are important
