### ISSUE TITLE
'throw ""' in console - does not return

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-node-debug#98]
This is a dumb bug but maybe there's something bigger behind it. If you eval `throw ""` in the console, then it won't show up in the console until you eval something else.

![oct-06-2016 17-14-46](https://cloud.githubusercontent.com/assets/323878/19175081/a5d1c9e4-8be8-11e6-925b-0999cf8b6b88.gif)

**Comment by weinand** [comment]
Works fine with node2, no intentions to fix this for legacy node-debug
