### ISSUE TITLE
process leak at cluster

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode-node-debug#99]
https://github.com/atian25/vscode-debug-cluster-test
- vscode 1.6
- app
  - start a child process, with `./worker` with debug port 5859
  - start a child process with `./agent`
- set `launch.json` with debug port 5859
- start debug, then stop it
- **only worker process is kill,  agent is leak.**
- https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/terminateProcess.sh

![image](https://cloud.githubusercontent.com/assets/227713/19265642/803f0270-8fd8-11e6-9608-7f29fc438e9c.png)

**Comment by weinand** [comment]
cluster debugging is not supported.
Pls see https://github.com/Microsoft/vscode/issues/3201

**Comment by atian25** [comment]
@weinand 
I can debug now due to vscode 1.6 debug port setting.
but the problem is `terminateProcess.sh` only kill the attached process
